# -*- coding: utf-8 -*-
"""
Al Sadat Builders — Area page content: housing societies + overseas Pakistanis.
Content is intentionally unique per area: terrain, approvals, plot sizes, logistics.
No fabricated project counts, testimonials, or statistics.
"""

SOCIETIES = [

# ============================================================
# BANI GALA
# ============================================================
{
    "slug": "construction-company-bani-gala",
    "name": "Bani Gala",
    "short": "Bani Gala",
    "group": "society",
    "icon": "⛰️",
    "title": "Construction Company in Bani Gala | Al Sadat Builders",
    "meta_desc": "Construction company in Bani Gala, Islamabad. Steep-plot foundations, RCC retaining walls, grey structure and turnkey villas. 30+ years. Free site survey.",
    "keywords": "construction company in Bani Gala, construction company Bani Gala Islamabad, builders in Bani Gala, house construction Bani Gala, contractor Bani Gala Islamabad, grey structure Bani Gala, retaining wall Bani Gala",
    "og_title": "Construction Company in Bani Gala Islamabad | Al Sadat Builders",
    "h1": "Construction Company in Bani Gala, Islamabad",
    "hero_sub": "Slope-Ready Foundations, RCC Retaining Walls, Grey Structure & Turnkey Villas on Rawal Lake Terrain",
    "badge": "Built for Bani Gala Terrain",
    "img": "images/banigala-hillside-villa.webp",
    "img_alt": "Hillside house construction in Bani Gala Islamabad by Al Sadat Builders",
    "lead_h2": "Building in Bani Gala Is Not the Same as Building in a CDA Sector",
    "intro": [
        "Bani Gala runs along the eastern edge of Islamabad, wrapped around the Rawal Lake catchment and the lower slopes of the Margalla foothills. Most of it is privately subdivided revenue land rather than a planned CDA sector — which means plots are irregular in shape, lanes are narrow, slopes are steep, and there is no single uniform building code you can simply follow.",
        "That terrain punishes contractors who build from a standard block plan. A Bani Gala plot needs a soil and slope assessment before the first line is marked, stepped footings that follow the ground instead of fighting it, retaining structures sized to real soil pressure, and drainage that carries Margalla runoff away from the foundation. Al Sadat Builders has worked this terrain for three decades, and every Bani Gala project we quote starts with that survey — not with a square-foot rate.",
    ],
    "highlight": "Key point: Bani Gala bylaw requirements vary plot by plot. Before we finalise any layout, we confirm which authority your specific plot falls under and what setbacks and excavation rules apply to it.",
    "stats": [
        ("30+", "Years Building in Islamabad"),
        ("RCC", "Retaining Walls & Stepped Footings"),
        ("100%", "Plot-Specific Bylaw Checks"),
        ("0", "Hidden Charges in Our BOQ"),
    ],
    "challenges_h2": "The Four Things That Decide a Bani Gala Build",
    "challenges_sub": "Get any one of these wrong and the problem shows up years later as cracks, settlement or water damage.",
    "challenges": [
        ("🌄", "Steep Slopes & Stepped Foundations",
         "Very few Bani Gala plots sit flat. We design stepped strip footings and cut-and-fill platforms so the structure follows the hill profile, with plinth beams tying the levels together."),
        ("🧱", "Retaining Walls Sized to Real Soil Pressure",
         "Downhill plots need reinforced RCC or gabion retaining walls with proper weep holes and backfill drainage. We size them against actual soil conditions rather than a rule of thumb."),
        ("💧", "Rainwater Runoff & Toe Drainage",
         "Storm water comes off the Margalla slopes fast. We build surface drains, toe drains and apron protection so runoff is carried past the foundation instead of undermining it."),
        ("🚚", "Narrow Lanes & Material Logistics",
         "Many Bani Gala access lanes cannot take a full-size mixer or dumper. We stage materials on site and use smaller delivery vehicles so concrete pours stay continuous without blocking neighbours."),
    ],
    "plots_h2": "What We Build in Bani Gala",
    "plots_sub": "From compact family homes on stepped plots to large terraced villas overlooking Rawal Lake.",
    "plots": [
        ("10 Marla Plots",
         "Mid-size family homes on moderate slopes, usually built as two storeys with a stepped ground floor to follow the natural level of the plot."),
        ("1 Kanal Houses",
         "The most common Bani Gala build. Full turnkey villas with independent water storage, septic systems and generous terraces facing the lake side."),
        ("2 Kanal & Farmhouse Style",
         "Large builds with wide spans, deep verandas and landscape integration. These need careful column layouts to avoid long unsupported spans on sloping ground."),
        ("Hillside Terrace Villas",
         "Multi-level homes cut into the slope with retaining walls on the uphill side and open terraces on the downhill side, designed so every level gets natural light."),
    ],
    "bylaws_h2": "Approvals & Site Rules in Bani Gala",
    "bylaws_sub": "Because Bani Gala is not a single-authority zone, the paperwork matters as much as the engineering.",
    "bylaws": [
        "Much of Bani Gala is private revenue land, so approvals generally route through the union council and Islamabad Capital Territory administration rather than CDA Building Control alone.",
        "Plots inside areas notified under CDA's Bani Gala scheme boundaries do require formal CDA submission, structural vetting and a completion certificate.",
        "Land inside the Rawal Lake catchment carries environmental restrictions on excavation depths, slope cutting and tree removal — we plan the site layout around those limits.",
        "Setbacks and maximum heights are influenced by the width of your access lane, so we confirm lane width and neighbour boundaries before drawing the layout.",
        "We prepare the complete drawing set — architectural, structural and services — and coordinate the submission on your behalf.",
    ],
    "faqs": [
        ("Can you build on a steep or sloped plot in Bani Gala?",
         "Yes. Sloped plots are the norm here, not the exception. We start with a soil and slope assessment, then design stepped footings, retaining walls and drainage specific to your plot. Building a standard flat-plot design on a Bani Gala slope is exactly the mistake that causes settlement cracks later."),
        ("What does construction cost in Bani Gala?",
         "Bani Gala generally sits above flat CDA-sector rates because of slope work, retaining structures and material handling on narrow lanes. We do not quote a flat per-square-foot figure — you get an itemised BOQ after a free on-site survey, with the slope and retaining work priced as separate line items so you can see exactly what the terrain is costing you."),
        ("Can you build on a plot with no municipal sewer connection?",
         "Yes. Large parts of Bani Gala are not on the municipal sewer network. We design and construct septic tanks and soakage pits sized to your household load, plus underground and overhead water storage, and we plan the tanker access route so it stays usable after the house is finished."),
        ("How long does a Bani Gala project take?",
         "Site preparation and slope work add time compared to a flat plot. As a working guide, grey structure typically runs several months and full turnkey construction longer, depending on plot size, slope severity and weather during the monsoon. We set a milestone calendar before work starts."),
    ],
    "nearby": ["f-7-islamabad", "f-6-islamabad", "gulberg-greens-islamabad", "dha-islamabad"],
    "cta_h2": "Get a Free Slope & Soil Assessment for Your Bani Gala Plot",
    "cta_p": "Send us your plot location and we will survey the slope, access and drainage, then give you an itemised BOQ.",
    "wa_text": "Hello Al Sadat Builders, I am looking for a construction company in Bani Gala Islamabad.",
},

# ============================================================
# DHA ISLAMABAD
# ============================================================
{
    "slug": "construction-company-dha-islamabad",
    "name": "DHA Islamabad",
    "short": "DHA Islamabad",
    "group": "society",
    "icon": "🏛️",
    "title": "Construction Company in DHA Islamabad | Al Sadat Builders",
    "meta_desc": "Construction company in DHA Islamabad — Phases 1, 2, 4, 5 & 6. Building Control approvals, basements, grey structure and turnkey villas. Free site visit.",
    "keywords": "construction company in DHA Islamabad, DHA Islamabad builders, house construction DHA Islamabad, construction contractor DHA Phase 2, DHA Phase 5 construction, basement construction DHA Islamabad",
    "og_title": "Construction Company in DHA Islamabad | Al Sadat Builders",
    "h1": "Construction Company in DHA Islamabad",
    "hero_sub": "Building Control Approvals, Basement Excavation, Grey Structure & Turnkey Villas Across Phases 1, 2, 4, 5 & 6",
    "badge": "DHA Building Control Experience",
    "img": "images/dha-luxury-villa.webp",
    "img_alt": "Luxury villa construction in DHA Islamabad by Al Sadat Builders",
    "lead_h2": "DHA Rewards Discipline — and Punishes Anyone Who Skips the Approvals",
    "intro": [
        "DHA Islamabad runs on its own Building Control Directorate, and its rules are enforced. Setback lines, covered-area ratios, height limits, basement depth, sewer connection procedure and the elevation design itself all have to be submitted and approved before a single shovel goes in. Work that starts without approval gets stopped — and rectifying it afterwards costs far more than doing it right the first time.",
        "Al Sadat Builders has built across DHA Phases 1, 2, 4, 5 and 6, and we prepare the submission set ourselves: architectural drawings, structural design, services layout and the elevation package. Because we handle both the paperwork and the execution, there is no gap between what was approved and what actually gets built on your plot.",
    ],
    "highlight": "Key point: We submit your drawings to DHA Building Control before mobilisation, and we build strictly to the approved set — so your completion certificate is not held up by unapproved deviations.",
    "stats": [
        ("30+", "Years in the Twin Cities"),
        ("Phases 1-6", "DHA Islamabad Coverage"),
        ("100%", "Approved-Drawing Compliance"),
        ("0", "Unpriced Extras Later"),
    ],
    "challenges_h2": "What Makes a DHA Build Different",
    "challenges_sub": "DHA is a planned society, but the execution rules are stricter and the inspection gates are real.",
    "challenges": [
        ("🏛️", "DHA Building Control Submission",
         "Architectural drawings, structural design, elevation package and services layout all go in as a set. We prepare and coordinate the submission rather than leaving you to run between consultants."),
        ("📐", "Setbacks, Coverage Ratio & Height Limits",
         "DHA enforces its own front, rear and side setback lines plus maximum covered area and height. We test the layout against those limits before finalising, so the design is approvable from the start."),
        ("🏗️", "Basement Excavation & Dewatering",
         "Basements are common on larger DHA plots. They need shoring design, a dewatering plan for the water table, and full tanking — not just a bitumen coat on the outside face."),
        ("🔐", "Labour Security Clearance & Site Discipline",
         "DHA requires cleared, documented labour and controlled site access. We maintain worker records, keep the site fenced and manage material movement so neighbours and society rules are respected."),
    ],
    "plots_h2": "What We Build in DHA Islamabad",
    "plots_sub": "From compact Phase 5 homes to large-format villas with basements in Phases 1 and 2.",
    "plots": [
        ("5 Marla in DHA Phase 5",
         "Efficient two-storey family homes on tighter plots, where stair placement, light wells and covered-area limits drive the whole floor plan."),
        ("10 Marla Houses",
         "The workhorse DHA plot. Two storeys plus a basement or servant quarter, with careful attention to setback compliance and street elevation approvals."),
        ("1 Kanal Villas",
         "Full turnkey villas with imported finishing, false ceilings, home automation conduits and landscaped frontage — designed to meet DHA's elevation expectations."),
        ("2 Kanal & Custom Builds",
         "Large-format residences with basement parking, wide spans, double-height lobbies and sometimes a separate guest or staff block on the same plot."),
    ],
    "bylaws_h2": "DHA Approvals & Compliance",
    "bylaws_sub": "The sequence matters as much as the drawings.",
    "bylaws": [
        "Building plan approval from the DHA Building Control Directorate is required before mobilisation, based on a complete drawing set including structural design.",
        "Setback lines, maximum covered area and height limits are set by DHA and vary by phase and plot size — we verify your specific plot before designing.",
        "Basements require a shoring and dewatering approach as part of the submission, not as an afterthought once excavation starts.",
        "Sewer and drainage connections must follow DHA's specified procedure, including inspection before backfilling.",
        "A completion certificate is issued only after DHA inspection confirms the built structure matches the approved drawings — which is why we build to the approved set without unapproved deviations.",
    ],
    "faqs": [
        ("Do you handle DHA Building Control approval, or do we need our own architect?",
         "We handle it. Al Sadat Builders prepares the architectural drawings, structural design, elevation package and services layout, then coordinates the submission to the DHA Building Control Directorate. If you already have an architect's design, we work from those drawings and prepare the structural and submission package around them."),
        ("Can you build a basement in DHA Islamabad?",
         "Yes. Basements are common on larger DHA plots and we build them regularly. The critical parts are shoring design for the excavation, a dewatering plan for the water table, and proper full tanking on the external faces. A thin bitumen coat on a basement wall is not waterproofing — moisture will find its way through and you will be dealing with damp and efflorescence for the life of the house."),
        ("How much does construction cost in DHA Islamabad?",
         "DHA sits at the upper end of Islamabad rates because of stricter finishing expectations, deeper excavation where basements are involved, and premium material specifications. We quote from an itemised BOQ with named material brands, not a blanket per-square-foot number, so you can see exactly where the money is going and adjust specifications deliberately."),
        ("Do you build in all DHA Islamabad phases?",
         "Yes — we work across Phases 1, 2, 4, 5 and 6. Each phase has its own bylaw nuances and inspection process, so tell us your phase and plot number when you enquire and we will confirm the specific requirements that apply."),
    ],
    "nearby": ["bahria-town-islamabad", "gulberg-greens-islamabad", "f-10-islamabad", "b-17-multi-gardens-islamabad"],
    "cta_h2": "Planning a Build in DHA Islamabad?",
    "cta_p": "Send us your phase and plot number. We will confirm the applicable bylaws and prepare an itemised BOQ.",
    "wa_text": "Hello Al Sadat Builders, I am looking for a construction company in DHA Islamabad.",
},

# ============================================================
# BAHRIA TOWN & ENCLAVE
# ============================================================
{
    "slug": "construction-company-bahria-town-islamabad",
    "name": "Bahria Town & Bahria Enclave",
    "short": "Bahria Town",
    "group": "society",
    "icon": "🏘️",
    "title": "Construction Company in Bahria Town | Al Sadat Builders",
    "meta_desc": "Construction company in Bahria Town and Bahria Enclave Islamabad. Design Wing approvals, hill-slope retention, rainwater harvesting and turnkey villas.",
    "keywords": "construction company in Bahria Town, construction company Bahria Enclave Islamabad, builders Bahria Town Rawalpindi, house construction Bahria Enclave, Bahria Design Wing approval contractor",
    "og_title": "Construction Company in Bahria Town & Bahria Enclave Islamabad",
    "h1": "Construction Company in Bahria Town & Bahria Enclave",
    "hero_sub": "Design Wing Approvals, Hill-Slope Retention, Rainwater Harvesting Compliance & Turnkey Construction",
    "badge": "Bahria Design Wing Experience",
    "img": "images/bahria-spanish-villa.webp",
    "img_alt": "Spanish style villa construction in Bahria Enclave Islamabad",
    "lead_h2": "Bahria Enclave's Hills Are Beautiful — and They Change How You Build",
    "intro": [
        "Bahria Town Rawalpindi and Bahria Enclave share a developer, but they are very different construction environments. Bahria Town's developed phases are largely flat and serviced, while Bahria Enclave is built into genuinely steep terrain where many plots required cut-and-fill before they could be handed over — and where the exposed cut faces and slope stability become your problem the moment you start excavating.",
        "On top of the terrain sits a formal approval process through the Bahria Design Wing, which reviews the architectural design and elevation before construction begins, plus mandatory rainwater harvesting and documented security clearance for site labour. Al Sadat Builders works through that process regularly: we prepare the design package for review, size the retaining and drainage works to the actual plot, and build to the approved design.",
    ],
    "highlight": "Key point: In Bahria Enclave we treat slope stability and drainage as structural work, not landscaping. Retaining walls, toe drains and cut-face protection go into the BOQ from day one.",
    "stats": [
        ("30+", "Years Construction Experience"),
        ("Design Wing", "Approval Package Prepared For You"),
        ("100%", "Rainwater Harvesting Compliance"),
        ("0", "Hidden Charges in Our BOQ"),
    ],
    "challenges_h2": "What We Handle Differently in Bahria",
    "challenges_sub": "Enclave and Bahria Town each bring their own set of execution constraints.",
    "challenges": [
        ("⛰️", "Hill Cutting, Cut Faces & Slope Retention",
         "Many Enclave plots sit on cut ground. We assess the exposed face, design reinforced retaining structures with proper backfill drainage, and protect the cut so it does not erode into your building line."),
        ("🏛️", "Bahria Design Wing Approval",
         "The architectural design and elevation must be reviewed and approved before construction. We prepare the design package to Bahria's submission requirements and coordinate the review so the build is not held up."),
        ("💧", "Rainwater Harvesting Compliance",
         "Bahria requires rainwater harvesting as part of the build. We design and construct the collection and recharge system into the plot layout rather than bolting it on afterwards."),
        ("🔐", "Labour Security Clearance & Site Access",
         "Bahria operates controlled entry. We maintain documented worker records and manage material delivery through the society's gate procedures so your site does not get flagged."),
    ],
    "plots_h2": "What We Build in Bahria",
    "plots_sub": "From compact town-phase homes to large villa designs on the Enclave hills.",
    "plots": [
        ("5 & 8 Marla Homes",
         "Common in the developed Bahria Town phases and the smaller Enclave sub-sectors — efficient two-storey layouts making full use of a tight footprint."),
        ("10 Marla Houses",
         "Two storeys with a basement or store, where the design has to satisfy Design Wing elevation expectations while working within plot coverage rules."),
        ("1 Kanal Villas",
         "Full turnkey builds with imported finishing, double-height entrances and landscaped terraces oriented to take in the hill views."),
        ("Slope & View Plots",
         "Plots on graded ground needing retaining walls, stepped floor levels and drainage designed together so the building and the hillside stay stable."),
    ],
    "bylaws_h2": "Bahria Approvals & Compliance",
    "bylaws_sub": "Bahria enforces its own design and construction rules independently of CDA and RDA.",
    "bylaws": [
        "Architectural design and elevation must be submitted to the Bahria Design Wing and approved before construction starts.",
        "Rainwater harvesting is a construction requirement in Bahria, not an optional upgrade — the system must be built into the plot.",
        "Site labour requires documented security clearance, and material movement follows the society's gate and timing procedures.",
        "Bahria Enclave plots on steep or cut terrain need slope stability and drainage works designed alongside the structure.",
        "Bahria Town Rawalpindi falls under RDA's wider jurisdiction, so certain submissions and completion requirements route through RDA — we confirm which applies to your plot.",
    ],
    "faqs": [
        ("Do you handle Bahria Design Wing approval?",
         "Yes. We prepare the architectural design, elevation package and supporting drawings to Bahria's submission format, then coordinate the Design Wing review. If you already have a design you like, we work from it and prepare the structural and submission documentation around it."),
        ("Is Bahria Enclave harder to build in than Bahria Town?",
         "The approvals process is similar, but the terrain is very different. Bahria Enclave's hills mean many plots sit on graded or cut ground, so retaining walls, toe drains and slope protection become part of the structural scope. On flat Bahria Town phases, that work is usually minimal. This is why an Enclave BOQ will always carry slope-related line items that a flat-phase BOQ will not."),
        ("How much does construction cost in Bahria Town or Enclave?",
         "Flat Bahria Town phases price close to standard Islamabad rates. Bahria Enclave generally prices higher because of slope work, retaining structures and material handling on graded roads. We quote from an itemised BOQ after a free on-site survey, with terrain work shown as separate line items."),
        ("Can you handle rainwater harvesting compliance?",
         "Yes. Rainwater harvesting is a construction requirement in Bahria, and we design and build the collection and recharge system into the plot during construction. Trying to add it after the house is finished usually means breaking finished surfaces, so it belongs in the original scope."),
    ],
    "nearby": ["dha-islamabad", "b-17-multi-gardens-islamabad", "gulberg-greens-islamabad", "overseas-pakistanis"],
    "cta_h2": "Building in Bahria Town or Bahria Enclave?",
    "cta_p": "Share your plot number and phase. We will confirm the Design Wing requirements and price the terrain work properly.",
    "wa_text": "Hello Al Sadat Builders, I want to build in Bahria Town or Bahria Enclave Islamabad.",
},

# ============================================================
# GULBERG GREENS
# ============================================================
{
    "slug": "construction-company-gulberg-greens-islamabad",
    "name": "Gulberg Greens & Residencia",
    "short": "Gulberg Greens",
    "group": "society",
    "icon": "🌿",
    "title": "Construction Company in Gulberg Greens | Al Sadat Builders",
    "meta_desc": "Construction company in Gulberg Greens and Residencia Islamabad. Farmhouse builds, large spans, boundary walls and turnkey villas on 1-4 Kanal plots.",
    "keywords": "construction company in Gulberg Greens, Gulberg Greens Islamabad builders, farmhouse construction Islamabad, Gulberg Residencia construction, 2 Kanal farmhouse builders Islamabad",
    "og_title": "Construction Company in Gulberg Greens Islamabad | Al Sadat Builders",
    "h1": "Construction Company in Gulberg Greens, Islamabad",
    "hero_sub": "Farmhouse Construction, Large-Span Structures, Perimeter Boundary Walls & Turnkey Builds on 1-4 Kanal Plots",
    "badge": "Farmhouse & Large-Plot Builders",
    "img": "images/grey-structure-site.webp",
    "img_alt": "Farmhouse grey structure construction in Gulberg Greens Islamabad",
    "lead_h2": "Big Plots Ask Different Questions",
    "intro": [
        "Gulberg Greens was planned as a farmhouse belt, and the plots show it. Instead of the 5 and 10 Marla footprints that dominate the rest of Islamabad, you are working with 1, 2, 4 Kanal and larger parcels — often with wide frontages and a lot of open ground around the building itself.",
        "That scale changes the engineering brief. Long unsupported spans need proper column and beam layouts rather than guesswork. A farmhouse also needs its own water supply strategy, its own sewerage or septic arrangement, a perimeter boundary wall with properly founded piers, and drainage across open ground that has nothing to do with a municipal system. Al Sadat Builders builds this scope as one coordinated package — structure, boundary, services and finishing — rather than leaving you to stitch together four different contractors.",
    ],
    "highlight": "Key point: On farmhouse plots, the perimeter boundary wall and gate structure are a structural build in their own right. Under-sizing the footings is one of the most common and most expensive mistakes on large plots.",
    "stats": [
        ("30+", "Years Construction Experience"),
        ("1-4 Kanal", "Farmhouse Plot Experience"),
        ("Long Span", "Column & Beam Design"),
        ("0", "Hidden Charges in Our BOQ"),
    ],
    "challenges_h2": "What We Handle Differently on Farmhouse Plots",
    "challenges_sub": "Large plots introduce scope that simply does not exist on a 5 Marla city plot.",
    "challenges": [
        ("📏", "Long Spans & Wide Frontages",
         "Wide farmhouse layouts invite long unsupported spans. We design the column and beam grid properly so the structure carries the load without excessive deflection or cracking."),
        ("🧱", "Perimeter Boundary Walls & Gate Piers",
         "A farmhouse perimeter is a long run of wall needing founded piers at correct intervals. We size footings to the wall height and soil, and build the gate structure as an engineered element."),
        ("💧", "Independent Water & Sewerage Strategy",
         "Farmhouse plots are usually outside municipal services. We plan bore water, underground and overhead storage, septic tanks and soakage pits as a complete system sized to the house."),
        ("🌧️", "Open-Ground Drainage & Ground Levels",
         "With nothing built around you, rainwater has to be directed deliberately. We set site levels and drainage falls so water moves away from the building and does not pond against the boundary."),
    ],
    "plots_h2": "What We Build in Gulberg Greens",
    "plots_sub": "Farmhouse and large-plot construction across Gulberg Greens and Gulberg Residencia.",
    "plots": [
        ("1 Kanal Builds",
         "The smaller end of the farmhouse range — often a main residence with a guest room, built with a proper boundary wall and gated entry."),
        ("2 Kanal Farmhouses",
         "Single or double storey with wide verandas, landscaped setbacks and separate staff or guest accommodation on the same plot."),
        ("4 Kanal & Above",
         "Large estates needing master planning across the plot: main house, outbuildings, long boundary runs, internal roads and full external services."),
        ("Gulberg Residencia Homes",
         "Standard residential plots in the Residencia blocks, built to the same structural standard as our city-sector work with tighter footprint planning."),
    ],
    "bylaws_h2": "Approvals & Compliance in Gulberg",
    "bylaws_sub": "Farmhouse zones have their own land-use and setback logic.",
    "bylaws": [
        "Gulberg operates under its own society administration with rules on plot coverage, building height and setback from the plot boundary — we confirm the specific requirements for your block.",
        "Farmhouse plots carry land-use conditions that limit how much of the plot can be built over, so the layout must be planned against the permitted coverage.",
        "Perimeter boundary wall heights and gate positions are subject to society rules, and we confirm these before construction rather than after.",
        "Service connections and sewerage arrangements follow the society's procedure for the specific block or phase.",
        "We prepare the drawing set and coordinate submission so the built structure matches what was approved.",
    ],
    "faqs": [
        ("Do you build farmhouses in Gulberg Greens?",
         "Yes. Farmhouse construction is a core part of our work in Gulberg Greens — single and double storey residences on 1, 2 and 4 Kanal plots, including the perimeter boundary wall, gate structure and full external services as one coordinated package."),
        ("Can you build the perimeter boundary wall as well as the house?",
         "Yes, and we recommend it as a single scope. The boundary wall, gate piers and the main building should share the same foundation design logic and the same site level plan. Splitting them between contractors is how you end up with a wall that settles away from the gate pier, or drainage that ponds against one side of the boundary."),
        ("How is farmhouse construction priced?",
         "Farmhouse pricing depends far more on scope than on plot size. A 2 Kanal plot with a modest single-storey house costs a fraction of the same plot built out with a double-storey residence and outbuildings. We quote from an itemised BOQ covering structure, boundary, services and finishing as separate sections so you can add or drop scope deliberately."),
        ("How long does a farmhouse take to build?",
         "Large plots take longer than city plots mainly because of the external scope — boundary walls, long drainage runs and independent service systems. Grey structure and turnkey timelines both extend with plot size and built-up area. We set a milestone calendar before mobilisation."),
    ],
    "nearby": ["bani-gala", "dha-islamabad", "b-17-multi-gardens-islamabad", "bahria-town-islamabad"],
    "cta_h2": "Building a Farmhouse in Gulberg Greens?",
    "cta_p": "Send us your plot size and block. We will survey the site and prepare a full BOQ including boundary and services.",
    "wa_text": "Hello Al Sadat Builders, I want to build a farmhouse in Gulberg Greens Islamabad.",
},

# ============================================================
# B-17 MULTI GARDENS
# ============================================================
{
    "slug": "construction-company-b-17-multi-gardens-islamabad",
    "name": "B-17 Multi Gardens",
    "short": "B-17 Multi Gardens",
    "group": "society",
    "icon": "🏡",
    "title": "Construction Company in B-17 Islamabad | Al Sadat Builders",
    "meta_desc": "Construction company in B-17 Multi Gardens (MPCHS) Islamabad. 5, 7 and 10 Marla house construction, grey structure and turnkey builds. Free site visit.",
    "keywords": "construction company in B-17 Islamabad, B-17 Multi Gardens builders, MPCHS construction contractor, 5 marla house construction B-17, 10 marla construction B-17 Islamabad",
    "og_title": "Construction Company in B-17 Multi Gardens Islamabad | Al Sadat Builders",
    "h1": "Construction Company in B-17 Multi Gardens, Islamabad",
    "hero_sub": "5 Marla, 7 Marla & 10 Marla House Construction, Grey Structure and Turnkey Builds in MPCHS B-17",
    "badge": "B-17 & MPCHS Builders",
    "img": "images/corner-house-islamabad.webp",
    "img_alt": "Corner house grey structure under construction in B-17 Multi Gardens Islamabad",
    "lead_h2": "B-17 Is a Young Sector — and That Changes the Build Sequence",
    "intro": [
        "B-17 Multi Gardens is developed by MPCHS and has grown quickly into one of the most active family-house sectors on the Islamabad side. A large share of the plots are 5, 7 and 10 Marla, which makes it a first-home and family-home market rather than a luxury villa market — and it means the majority of builds here are new construction rather than renovation.",
        "New sectors bring their own practical problems. Infrastructure and road work can still be progressing around you, water supply is not always reliable year-round, and neighbour construction is happening on all sides at once. Al Sadat Builders plans around that reality: we design a water storage strategy that does not assume a constant supply, sequence our work so we are not blocked by adjacent site activity, and keep the site organised so material does not disappear into the sector's general construction traffic.",
    ],
    "highlight": "Key point: In a still-developing sector, your water storage capacity is not a luxury — it is your buffer against supply interruptions. We size underground and overhead tanks generously as standard in B-17.",
    "stats": [
        ("30+", "Years Construction Experience"),
        ("5-10 Marla", "B-17 Plot Range"),
        ("Grade 60", "Certified Rebar Only"),
        ("0", "Hidden Charges in Our BOQ"),
    ],
    "challenges_h2": "What We Handle Differently in B-17",
    "challenges_sub": "A developing sector is a different working environment from an established one.",
    "challenges": [
        ("🚰", "Water Supply Reliability & Storage Sizing",
         "Supply in developing sectors is not always constant. We size underground and overhead storage generously so the household runs normally through interruptions, and plan bore provision where it is feasible."),
        ("🚧", "Adjacent Construction & Site Access",
         "With neighbours building on both sides, access and material staging need coordination. We sequence deliveries and work activity so your site keeps moving without blocking the street."),
        ("💰", "Value-Conscious Material Specification",
         "B-17 is a family-home market, so the goal is maximum structural quality at a sensible cost. We specify proven branded materials and put the savings into structure and waterproofing rather than imported finishes you did not ask for."),
        ("💧", "Damp-Proofing & Waterproofing Discipline",
         "Newer sectors with active surrounding construction and fresh groundworks are unforgiving about damp. We install full DPC, basement or plinth tanking where relevant, and roof waterproofing as part of the build."),
    ],
    "plots_h2": "What We Build in B-17 Multi Gardens",
    "plots_sub": "Straightforward, well-built family homes with the structure and waterproofing done properly.",
    "plots": [
        ("5 Marla Houses",
         "The most common B-17 plot. Efficient two-storey layouts with careful stair placement and light wells to make a compact plot feel open."),
        ("7 Marla Houses",
         "A comfortable family footprint allowing a proper lounge, three bedrooms and a usable covered car porch without squeezing the plan."),
        ("10 Marla Houses",
         "Room for a basement or store, a wider frontage and separate guest space, with the structural design to match the larger span."),
        ("Grey Structure Only",
         "For owners who want to complete finishing themselves in stages — we build the full grey structure to spec and hand over with a clean, documented shell."),
    ],
    "bylaws_h2": "Approvals & Compliance in B-17",
    "bylaws_sub": "MPCHS administers B-17 with CDA oversight on the wider sector layout.",
    "bylaws": [
        "MPCHS operates its own building rules on setbacks, coverage and height, running alongside CDA's wider oversight — we confirm the applicable requirements for your block and street.",
        "Building plan approval is required before mobilisation, based on the full architectural and structural drawing set.",
        "Street width affects permissible building height, so we verify your street and plot position before finalising the design.",
        "Service connections follow the sector's specified procedure for water, sewer and drainage.",
        "We prepare the drawing set and coordinate submission so the built structure matches the approved design at completion.",
    ],
    "faqs": [
        ("What does it cost to build a 5 Marla house in B-17?",
         "It depends on specification, but we do not quote a blanket per-square-foot figure. We provide an itemised BOQ with named material brands after a free site visit, covering grey structure and finishing as separate sections. That lets you see the cost of each stage and decide where to upgrade and where standard specification is perfectly adequate."),
        ("Do you only build complete houses, or can you do grey structure only?",
         "Both. A large number of B-17 clients choose grey structure first and finish in stages as budget allows. We build the complete grey structure to specification and hand over a clean, documented shell — so when you are ready to finish, we or any other contractor can pick up from a known, sound state."),
        ("How long does a 5 or 10 Marla house take in B-17?",
         "Timelines depend on plot size, storeys and weather during the monsoon. We set a milestone calendar before mobilisation covering excavation, foundation, each slab, masonry, plaster and finishing stages, so you always know what is happening next and what payment is tied to it."),
        ("Can you manage the build while I am living abroad?",
         "Yes. A significant share of our clients are overseas Pakistanis. We provide scheduled video progress calls, photographic material delivery records, milestone-linked payments through formal bank accounts and a full digital ledger. See our dedicated overseas Pakistanis page for the full process."),
    ],
    "nearby": ["dha-islamabad", "bahria-town-islamabad", "gulberg-greens-islamabad", "overseas-pakistanis"],
    "cta_h2": "Building in B-17 Multi Gardens?",
    "cta_p": "Tell us your plot size and street. We will visit the site and prepare an itemised BOQ.",
    "wa_text": "Hello Al Sadat Builders, I want to build a house in B-17 Multi Gardens Islamabad.",
},

# ============================================================
# CDA SECTORS HUB
# ============================================================
{
    "slug": "construction-company-cda-sectors-islamabad",
    "name": "CDA Sectors",
    "short": "CDA Sectors",
    "group": "society",
    "icon": "🏙️",
    "title": "Construction Company in CDA Sectors | Al Sadat Builders",
    "meta_desc": "Construction company in CDA sectors Islamabad — F-6, F-7, F-8, F-10, F-11, G-6, G-9, G-10, G-11, E-11. Approvals, rebuilds and renovation. 30+ years.",
    "keywords": "construction company in CDA sectors Islamabad, CDA sector builders Islamabad, house construction F-7 Islamabad, construction company G-11 Islamabad, CDA building control approved contractor",
    "og_title": "Construction Company in CDA Sectors Islamabad | Al Sadat Builders",
    "h1": "Construction Company in CDA Sectors, Islamabad",
    "hero_sub": "CDA Building Control Approvals, Structural Rebuilding, Renovation & New Construction Across Islamabad's Planned Sectors",
    "badge": "CDA Building Control Experience",
    "img": "images/hero-construction.webp",
    "img_alt": "House construction in a CDA sector Islamabad by Al Sadat Builders",
    "lead_h2": "Islamabad's CDA Sectors Are Not One Market — They Are Several",
    "intro": [
        "The CDA sectors are the original planned heart of Islamabad, and they were built in waves. F-6, F-7 and G-6 went up first and now hold some of the oldest housing stock in the city. F-10, F-11 and G-11 came later. E-11 is newer still, with plots that were only built out more recently. Each wave brings a different dominant project type.",
        "In the older sectors, the work is usually renovation, extension or a full structural rebuild behind a retained facade — because the land value has long since outgrown the building on it. In the newer sectors, the work is more often a first build on a plot that is still empty. Al Sadat Builders works across both: restoring and extending load-bearing structures where that is the right answer, and designing new RCC frames where a rebuild is the better investment.",
    ],
    "highlight": "Key point: In older CDA sectors we survey the existing structure before recommending anything. Sometimes renovation is the correct answer; sometimes rebuilding is genuinely cheaper than repeatedly repairing a failing frame. We tell you which, with the reasoning.",
    "stats": [
        ("30+", "Years in Islamabad"),
        ("10+", "CDA Sectors Covered"),
        ("100%", "CDA Bylaw Compliance"),
        ("0", "Hidden Charges in Our BOQ"),
    ],
    "challenges_h2": "What We Handle Differently in CDA Sectors",
    "challenges_sub": "Old stock, strict bylaws and tight plots each change the approach.",
    "challenges": [
        ("🏛️", "CDA Building Control Compliance",
         "Setback lines, covered-area ratio, height limits, structural vetting and completion certificate protocol. We prepare the submission set and build to the approved drawings."),
        ("🔍", "Surveying Ageing Structures",
         "Many older sector homes have 40-year-old load-bearing walls, corroded wiring and undersized services. We assess what can be retained and what genuinely needs replacing before quoting."),
        ("🧱", "Load-Bearing vs RCC Frame Decisions",
         "Older houses use load-bearing brick walls that limit how far you can open a plan. We explain honestly when a wall can be removed with a proper beam and when opening it would compromise the structure."),
        ("🚧", "Narrow Streets & Limited Site Access",
         "Sector plots sit on 30 and 40 foot roads with tight frontages. Excavation spoil, concrete delivery and crane placement all need planning so the street stays usable for your neighbours."),
    ],
    "plots_h2": "What We Build in CDA Sectors",
    "plots_sub": "From complete rebuilds in F-6 and G-6 to first builds in E-11 and G-11.",
    "plots": [
        ("10 Marla Houses",
         "Common across G-6, G-9, G-10 and G-11. Often a rebuild or a substantial renovation with a modern plan fitted inside the original footprint."),
        ("1 Kanal Residences",
         "The standard in F-6, F-7, F-8 and F-10. Frequently a full structural rebuild that retains the street address while delivering an entirely modern home."),
        ("Older Sector Rebuilds",
         "Where the original 1970s or 80s structure cannot support the plan you want, we design a new RCC frame on the same plot under CDA approval."),
        ("Renovation & Extension",
         "Kitchen and bathroom remodelling, second-storey additions, structural crack repair and full service replacement for houses being kept rather than rebuilt."),
    ],
    "bylaws_h2": "CDA Approvals & Compliance",
    "bylaws_sub": "Islamabad's planned sectors are governed by CDA Building Control.",
    "bylaws": [
        "Building plan approval from CDA is required before construction, based on a complete architectural and structural drawing set.",
        "Setback lines, maximum covered area and permissible building height are set by CDA and vary by sector, street width and plot size.",
        "Structural design must satisfy Islamabad's seismic zone requirements, and structural vetting applies to the submitted design.",
        "A completion certificate is issued after CDA inspection confirms the structure matches the approved drawings without unauthorised deviations.",
        "Where a plot has an older structure, demolition and rebuild follows CDA's procedure for the sector rather than being treated as an internal matter.",
    ],
    "faqs": [
        ("Which CDA sectors do you cover?",
         "We cover the CDA sectors across Islamabad, with dedicated pages for F-6, F-7, F-8, F-10, F-11, G-6, G-9, G-10, G-11 and E-11. We also work in the wider E, F, G, H and I series where plot conditions suit our methods. Pick your sector from the list below for sector-specific guidance."),
        ("Is it cheaper to renovate or rebuild an old CDA sector house?",
         "It depends entirely on the condition of the existing structure, and we will tell you honestly after inspecting it. If the frame is sound, renovation or extension is usually the better investment. If the footings are undersized, the brickwork is degrading, and the services need complete replacement, then a rebuild often costs less over a ten-year horizon than repeatedly repairing a failing structure. We put that comparison in writing rather than pushing you toward the larger job."),
        ("Do you handle CDA Building Control approval?",
         "Yes. We prepare the architectural drawings, structural design and services layout, then coordinate the CDA submission and build strictly to the approved set. Building without approval risks a stop-work notice and delays the completion certificate, so it is not a corner worth cutting."),
        ("Can you add a second storey to an existing house in a CDA sector?",
         "Usually yes, but only after checking the existing foundations and walls. Older sector houses were often designed for a single storey, so the footings may need strengthening before additional load is applied. We inspect first, then design the addition and the strengthening together."),
    ],
    "nearby": ["f-6-islamabad", "f-7-islamabad", "g-6-islamabad", "e-11-islamabad"],
    "cta_h2": "Building or Renovating in a CDA Sector?",
    "cta_p": "Tell us your sector and plot number. We will confirm the CDA requirements and prepare an itemised BOQ.",
    "wa_text": "Hello Al Sadat Builders, I need construction work in a CDA sector in Islamabad.",
},

# ============================================================
# OVERSEAS PAKISTANIS
# ============================================================
{
    "slug": "construction-company-overseas-pakistanis",
    "name": "Overseas Pakistanis",
    "short": "Overseas Pakistanis",
    "group": "special",
    "icon": "✈️",
    "title": "Build House in Pakistan From Abroad | Al Sadat Builders",
    "meta_desc": "Building a house in Islamabad from abroad? We manage overseas Pakistani construction with weekly video calls, recorded deliveries and milestone payments.",
    "keywords": "overseas Pakistani construction company islamabad, build house in pakistan from abroad, construction management overseas pakistanis, house construction for overseas pakistanis islamabad, nri construction pakistan",
    "og_title": "Construction for Overseas Pakistanis | Al Sadat Builders Islamabad",
    "h1": "Building Your House in Islamabad From Abroad",
    "hero_sub": "Weekly Video Progress Calls, Recorded Material Deliveries and Milestone-Linked Payments — Managed by the Founder Personally",
    "badge": "Remote Build Management",
    "img": "images/hero-construction.webp",
    "img_alt": "Overseas Pakistani clients receiving video progress updates from an Islamabad construction site",
    "lead_h2": "The Real Risk Is Not Distance — It Is Not Knowing What Is Happening",
    "intro": [
        "Every overseas client we work with is worried about the same thing: sending money to Pakistan and having no idea what it is actually being spent on. That is a reasonable fear. A build that is not being watched can quietly drift on quantity of steel, cement brand, slab thickness and waterproofing — and you will only find out when you visit years later and the cracks appear.",
        "Al Sadat Builders manages overseas projects around a simple principle: you should never have to ask what happened this week. You get a fixed reporting schedule, a video walkthrough on a set day, photographs dated and tied to physical progress, and material delivery records you can match against your own ledger. Payments release against completed, inspected milestones rather than a monthly demand.",
    ],
    "highlight": "Key point: Payments are linked to milestones that have already been completed and recorded on video — not to a schedule. If a milestone has not been reached, it is not billed.",
    "stats": [
        ("Weekly", "Video Progress Walkthroughs"),
        ("Milestone", "Linked Payment Releases"),
        ("Recorded", "Material Delivery Documentation"),
        ("0", "Unrecorded Site Spending"),
    ],
    "challenges_h2": "How We Remove the Distance Problem",
    "challenges_sub": "Four concrete mechanisms that replace being physically present on site.",
    "challenges": [
        ("📹", "Scheduled Weekly Video Calls",
         "A fixed day and time each week — 30 to 45 minutes, walking the site with you. You see the slab, the steel spacing, the plaster, the finishing. No waiting for you to chase an update."),
        ("📦", "Dated Material Delivery Records",
         "Every cement, steel and aggregate delivery is photographed with the delivery challan, and the records are shared with you. You can reconcile them against what you have paid for."),
        ("🏦", "Milestone-Linked Bank Payments",
         "Funds move through formal banking against completed milestones, not cash demands. Each release has a documented basis: what was finished, what was verified, what comes next."),
        ("🧾", "Written BOQ & Variation Control",
         "You sign off an itemised BOQ before mobilisation. Any genuine variation is documented and priced before the work is done, so the final account does not surprise you."),
    ],
    "plots_h2": "What Overseas Clients Usually Build",
    "plots_sub": "Most overseas projects fall into one of these four patterns.",
    "plots": [
        ("Family Home for Return",
         "A full turnkey house you intend to live in when you move back, built to a specification you would choose for your own permanent home — often 10 Marla or 1 Kanal."),
        ("Investment Build",
         "A practical, well-built house designed for rental yield rather than personal taste, with specification choices driven by what the local rental market actually values."),
        ("Grey Structure First",
         "Many overseas owners build the structure while funds are available and complete finishing later, spreading the cost across visits or across a longer savings period."),
        ("Finishing & Repair Only",
         "A house built earlier by someone else, now needing proper plaster, waterproofing, tile work and finishing brought up to standard."),
    ],
    "bylaws_h2": "Managing Land, Papers & Authority Approvals From Abroad",
    "bylaws_sub": "Physical distance should not mean legal or procedural gaps.",
    "bylaws": [
        "We coordinate the building plan submission with the relevant authority — CDA, DHA, Bahria Design Wing or the sector administration — and keep you copied on the approval status.",
        "Where an attorney or a family member is acting on your behalf locally, we work with them directly and document every instruction given.",
        "All payments are structured for formal banking channels so there is a clean, auditable record on both sides.",
        "Site security, labour documentation and material storage are managed on your behalf, with the site secured between working hours.",
        "On completion we hand over the full drawing set, material records and the documentation needed for your completion certificate and utility connections.",
    ],
    "faqs": [
        ("How do I monitor construction if I live in the UK, USA, Canada or the Gulf?",
         "You get a scheduled weekly video walkthrough on a fixed day and time, chosen to suit your time zone. We walk the site with you, show you the work in progress, and answer questions live. Between calls, dated photographs of material deliveries and completed stages are shared with you so there is a continuous record rather than a weekly snapshot."),
        ("How do payments work for overseas clients?",
         "Payments are milestone-linked rather than calendar-based. Before mobilisation you approve an itemised BOQ with the milestone schedule. When a milestone is completed and verified on video, the corresponding payment is released through formal banking. If a milestone has not been reached, it is not billed."),
        ("Can you take over a half-finished house that another contractor abandoned?",
         "Yes, and this is a common request. We survey the existing structure first — checking footings, column alignment, steel quality and concrete condition where it can be assessed — and give you an honest written assessment of what can be kept and what needs remediation before we quote for completing it."),
        ("Do you work with my family member or attorney in Pakistan?",
         "Yes. Many overseas clients have a relative or a local attorney handling day-to-day matters. We work with them directly, copy you on instructions, and document decisions in writing so there is a single record that everyone can see. We do not take verbal instructions from a third party that contradict what you have approved."),
        ("How much should I budget for construction in Islamabad?",
         "It depends on plot size and specification level, and rates move with steel and cement prices. We do not publish a single number that will be wrong by the time you read it. Send us your plot details and we will give you an itemised BOQ with current material rates and named brands, which you can compare directly against other quotes."),
    ],
    "nearby": ["dha-islamabad", "bahria-town-islamabad", "bani-gala", "b-17-multi-gardens-islamabad"],
    "cta_h2": "Building in Pakistan From Abroad?",
    "cta_p": "Send us your plot details and time zone. We will schedule a free consultation at a time that works for you.",
    "wa_text": "Hello Al Sadat Builders, I am an overseas Pakistani and want to build a house in Islamabad.",
    "is_overseas": True,
},

]
