# -*- coding: utf-8 -*-
"""
Al Sadat Builders — CDA sector page content: F, G and E series sectors.
Each sector differs by housing-stock age, plot sizes, street width, market type
(renovation vs first-build) and adjacency. No fabricated project counts or statistics.
"""

SECTORS = [

# ============================================================
# F-6
# ============================================================
{
    "slug": "construction-company-f-6-islamabad",
    "name": "F-6",
    "short": "F-6 Islamabad",
    "group": "sector",
    "icon": "🌳",
    "title": "Construction Company in F-6 Islamabad | Al Sadat Builders",
    "meta_desc": "Construction company in F-6 Islamabad. Structural rebuilds, renovation, extension and new construction on 1-2 Kanal plots. CDA approvals handled.",
    "keywords": "construction company in F-6 Islamabad, F-6 Islamabad builders, house construction F-6, house renovation F-6 Islamabad, F-6 Kohsar Market contractor, rebuild house F-6",
    "og_title": "Construction Company in F-6 Islamabad | Al Sadat Builders",
    "h1": "Construction Company in F-6, Islamabad",
    "hero_sub": "Structural Rebuilds, Renovation & New Construction on Islamabad's Oldest and Most Established Sector",
    "badge": "F-6 Rebuild & Renovation",
    "img": "images/dha-luxury-villa.webp",
    "img_alt": "House rebuild and renovation construction in F-6 Islamabad",
    "lead_h2": "In F-6, You Are Almost Always Working Around an Existing House",
    "intro": [
        "F-6 was among the first sectors CDA developed, and its housing stock shows it. Many properties around Kohsar Market and the surrounding sub-sectors still sit on original 1960s and 1970s structures — load-bearing brick walls, shallow footings designed for a single storey, and services that have been patched repeatedly over five decades.",
        "At the same time, F-6 land is among the most expensive in Islamabad. That combination produces a very specific kind of project: owners who want a modern home but are deciding whether to renovate the existing structure, extend it upward, or demolish and rebuild entirely. Al Sadat Builders does all three in F-6, and we start every one of them with a structural assessment rather than an assumption.",
    ],
    "highlight": "Key point: In F-6 we inspect the existing footings before recommending a second storey. A 1970s single-storey foundation is often not sized for the additional load, and strengthening it later is far more expensive than planning for it now.",
    "stats": [
        ("30+", "Years in Islamabad"),
        ("1-2 Kanal", "Typical F-6 Plot Size"),
        ("100%", "CDA Approval Compliance"),
        ("0", "Hidden Charges in Our BOQ"),
    ],
    "challenges_h2": "What Makes F-6 Projects Unusual",
    "challenges_sub": "Old structures, high land value and mature street planting all shape what happens on site.",
    "challenges": [
        ("🔍", "Assessing 1970s Load-Bearing Structures",
         "Original F-6 houses use load-bearing brick walls and footings sized for one storey. Before we quote anything, we inspect the foundation depth, wall condition and whether an upward extension is structurally viable."),
        ("🧱", "Renovate, Extend or Rebuild — Honestly Compared",
         "With F-6 land values where they are, a rebuild is often the better investment — but not always. We put the structural findings and a cost comparison in writing so the decision is yours, not ours."),
        ("🌳", "Mature Trees & Excavation Constraints",
         "F-6 streets are heavily planted, and mature tree roots extend well past the trunk. Excavation and demolition need care to avoid destabilising street trees and neighbouring foundations."),
        ("📐", "Setbacks Against an Existing Older Footprint",
         "An existing house may sit closer to the boundary than current CDA setback rules allow. Rebuilding to today's rules can shrink your footprint compared to the house standing there now — we confirm this before design begins."),
    ],
    "plots_h2": "What We Build in F-6",
    "plots_sub": "Rebuild, renovate or extend — the right answer depends on the structure already on the plot.",
    "plots": [
        ("Full Structural Rebuild",
         "Demolition of the original structure and construction of a new RCC-framed house on the same plot, designed and approved under current CDA rules."),
        ("Second-Storey Extension",
         "Where the existing footings can carry the additional load, we build upward with independent column framing and connect the two levels properly."),
        ("Renovation & Modernisation",
         "Complete interior modernisation — kitchens, bathrooms, services, wiring, plumbing and finishes — while retaining a structure that is still sound."),
        ("1 & 2 Kanal Residences",
         "Large-format family homes with guest blocks, basements and landscaped grounds, built to contemporary standards behind the original street line."),
    ],
    "bylaws_h2": "CDA Approvals in F-6",
    "bylaws_sub": "Older sectors often have a gap between the standing structure and today's rules.",
    "bylaws": [
        "Building plan approval from CDA Building Control is required for any rebuild or structural extension, based on a full architectural and structural drawing set.",
        "Current setback lines and covered-area limits may be tighter than those the original house was built under — we confirm what applies to your plot before designing.",
        "Structural design must satisfy Islamabad's seismic zone requirements and is subject to structural vetting.",
        "Demolition of an existing structure follows CDA's procedure, including approvals and safe disposal of debris.",
        "A completion certificate requires CDA inspection confirming the built structure matches the approved drawings.",
    ],
    "faqs": [
        ("Should I renovate or rebuild my old house in F-6?",
         "It comes down to the condition of the original structure. If the footings are sound and the brickwork is not degrading, renovation or a controlled extension is usually the sensible investment. If the footings are undersized for anything beyond one storey, the services need complete replacement, and the walls are showing ongoing damp and cracks, then a rebuild often costs less over ten years than repeated repairs. We inspect first and give you the comparison in writing."),
        ("Can you add a second storey to my F-6 house?",
         "Frequently yes, but it must be verified rather than assumed. We inspect the existing foundation and walls, and where the footings are insufficient we design the strengthening work alongside the extension. Adding a full storey onto a 1970s single-storey foundation without checking is how structural cracking starts."),
        ("Do you handle CDA approval for a rebuild in F-6?",
         "Yes. We prepare the architectural drawings, structural design and services layout, coordinate the CDA submission, and build strictly to the approved set. One thing to plan for: current setback rules may require a smaller footprint than the existing house, so the rebuild design has to work within today's limits rather than the original ones."),
    ],
    "nearby": ["f-7-islamabad", "f-8-islamabad", "g-6-islamabad", "bani-gala"],
    "cta_h2": "Rebuilding or Renovating in F-6?",
    "cta_p": "We will inspect the existing structure and tell you honestly whether it can be saved or should be rebuilt.",
    "wa_text": "Hello Al Sadat Builders, I need construction work in F-6 Islamabad.",
},

# ============================================================
# F-7
# ============================================================
{
    "slug": "construction-company-f-7-islamabad",
    "name": "F-7",
    "short": "F-7 Islamabad",
    "group": "sector",
    "icon": "🏙️",
    "title": "Construction Company in F-7 Islamabad | Al Sadat Builders",
    "meta_desc": "Construction company in F-7 Islamabad. House construction, rebuilds and high-end renovation on 1 Kanal plots around Jinnah Super and F-7 Markaz.",
    "keywords": "construction company in F-7 Islamabad, F-7 Islamabad builders, house construction F-7, F-7 Markaz Jinnah Super contractor, house rebuild F-7 Islamabad, 1 kanal construction F-7",
    "og_title": "Construction Company in F-7 Islamabad | Al Sadat Builders",
    "h1": "Construction Company in F-7, Islamabad",
    "hero_sub": "High-End Rebuilds, Renovation & New Construction Around Jinnah Super and the F-7 Sub-Sectors",
    "badge": "F-7 High-End Builds",
    "img": "images/dha-luxury-villa.webp",
    "img_alt": "High-end house construction and rebuild in F-7 Islamabad",
    "lead_h2": "F-7 Sets the Bar for Finish Quality — Because the Street Does",
    "intro": [
        "F-7 sits at the centre of Islamabad's most established residential addresses, anchored by Jinnah Super Market on the F-7 Markaz. The plot sizes are generous, mostly 1 Kanal and above, and the surrounding housing stock has been steadily rebuilt over the last two decades into contemporary residences. That means the visual standard on your street is high, and a build that looks out of place is noticeable immediately.",
        "Most F-7 work is therefore a rebuild or a substantial renovation rather than a first build. Al Sadat Builders approaches these projects around three things that matter here: elevation design that fits the street, finishing quality that matches the neighbourhood, and structural work — footings, tanking, spans — done to a standard that supports the finishes rather than undermining them after two monsoons.",
    ],
    "highlight": "Key point: The expensive failures in F-7 are never the visible finishes. They are the waterproofing, the plinth protection and the drainage detailing underneath them — which is where we put disproportionate attention.",
    "stats": [
        ("30+", "Years in Islamabad"),
        ("1 Kanal+", "Typical F-7 Plot Size"),
        ("100%", "CDA Approval Compliance"),
        ("0", "Hidden Charges in Our BOQ"),
    ],
    "challenges_h2": "What Makes F-7 Projects Demanding",
    "challenges_sub": "High specification raises the cost of every hidden mistake.",
    "challenges": [
        ("🎨", "Elevation Design & Street Fit",
         "F-7 frontages are visible and scrutinised. We design elevations that read as contemporary without clashing with the surrounding architecture, and that satisfy CDA's submission requirements."),
        ("💧", "Waterproofing Behind Expensive Finishes",
         "Imported stone, large-format porcelain and timber finishes are ruined by a single damp failure. Full tanking, plinth protection and roof waterproofing are non-negotiable parts of the scope, not optional extras."),
        ("📐", "Large Spans & Structural Openness",
         "Modern F-7 layouts want open ground floors and double-height spaces. Those need properly engineered beams and columns rather than walls removed after the fact to create an opening."),
        ("🚧", "Working on a Busy Residential Street",
         "F-7 streets are narrow relative to the plot sizes and carry constant traffic. Excavation spoil removal, concrete delivery and material staging all need tight scheduling to keep the street usable."),
    ],
    "plots_h2": "What We Build in F-7",
    "plots_sub": "Rebuilds and high-specification renovations across F-7/1 through F-7/4.",
    "plots": [
        ("Full Structural Rebuild",
         "Demolition and construction of a new residence on the same plot, with a contemporary elevation designed within current CDA setback and height limits."),
        ("1 Kanal Villas",
         "The dominant F-7 plot size — two storeys, often with a basement, guest accommodation and landscaped frontage finished to a high standard."),
        ("2 Kanal & Larger",
         "Substantial residences with wide frontages, double-height entrances, home automation conduits and full landscape integration."),
        ("High-End Renovation",
         "Complete interior rebuild of a sound structure — imported sanitary, custom joinery, false ceilings and full service replacement — without touching the frame."),
    ],
    "bylaws_h2": "CDA Approvals in F-7",
    "bylaws_sub": "Approval in F-7 is routine but the drawing set has to be complete and correct.",
    "bylaws": [
        "Building plan approval from CDA Building Control is required for rebuilds, extensions and any change to the approved structure.",
        "Setback lines, covered-area ratio and maximum height apply to your specific plot and street — we verify before designing the footprint.",
        "The elevation package forms part of the submission and must meet CDA's requirements, not just your own taste.",
        "Structural design must satisfy Islamabad's seismic zone requirements and is subject to vetting.",
        "Completion certificates are issued only after CDA inspection confirms the built structure matches what was approved.",
    ],
    "faqs": [
        ("How much does it cost to build a 1 Kanal house in F-7?",
         "F-7 sits at the upper end of Islamabad construction rates because finishing expectations here are high and structural spans are larger. We quote from an itemised BOQ with named material brands so you can see the cost of each stage and decide deliberately where to specify premium and where standard specification is genuinely adequate. A blanket per-square-foot number hides exactly the decisions that matter."),
        ("Do you handle the CDA elevation approval for an F-7 rebuild?",
         "Yes. We prepare the architectural drawings including the elevation package, the structural design and the services layout, then coordinate the CDA submission. Because we also build the project, there is no gap between the approved elevation and what actually gets constructed on the plot."),
        ("Can you rebuild while keeping the same plot boundaries?",
         "Yes. A rebuild on the same plot is the most common F-7 project. The one thing to check early is that current CDA setback rules may permit a smaller built footprint than the original house occupied — we confirm this before design begins so there are no surprises once demolition is done."),
    ],
    "nearby": ["f-6-islamabad", "f-8-islamabad", "f-10-islamabad", "bani-gala"],
    "cta_h2": "Building or Rebuilding in F-7?",
    "cta_p": "Send us your plot details and we will confirm the CDA limits and prepare an itemised BOQ.",
    "wa_text": "Hello Al Sadat Builders, I need construction work in F-7 Islamabad.",
},

# ============================================================
# F-8
# ============================================================
{
    "slug": "construction-company-f-8-islamabad",
    "name": "F-8",
    "short": "F-8 Islamabad",
    "group": "sector",
    "icon": "🕌",
    "title": "Construction Company in F-8 Islamabad | Al Sadat Builders",
    "meta_desc": "Construction company in F-8 Islamabad. House construction, rebuilds, basements and renovation near Faisal Mosque and F-8 Markaz. CDA approvals handled.",
    "keywords": "construction company in F-8 Islamabad, F-8 Islamabad builders, house construction F-8, F-8 Markaz contractor, house renovation F-8 Islamabad, construction near Faisal Mosque",
    "og_title": "Construction Company in F-8 Islamabad | Al Sadat Builders",
    "h1": "Construction Company in F-8, Islamabad",
    "hero_sub": "Construction, Rebuilds & Renovation Across F-8/1 to F-8/4, Near Faisal Mosque and F-8 Markaz",
    "badge": "F-8 Construction & Renovation",
    "img": "images/dha-luxury-villa.webp",
    "img_alt": "House construction and renovation in F-8 Islamabad near Faisal Mosque",
    "lead_h2": "F-8 Mixes Large Residential Plots With an Institutional Edge",
    "intro": [
        "F-8 is best known for Faisal Mosque, and the sector's character reflects that proximity. It holds a mix of large residential plots alongside institutional and office use, particularly along Jinnah Avenue and around the F-8 Markaz. The residential blocks run from F-8/1 through F-8/4, with generous plot sizes and a quieter feel than F-7's commercial frontage.",
        "That mix shapes the work. Plots here are large enough for substantial houses with wide spans and generous setbacks, so the structural design carries more weight than on a compact sector plot. At the same time, the presence of professional offices and institutional buildings nearby means site discipline — noise timing, dust control, access — matters more than usual. Al Sadat Builders plans for both.",
    ],
    "highlight": "Key point: On larger F-8 plots, wide spans and open plans are the norm. We design the column grid and beam depths for the loads they actually carry rather than adapting a standard layout.",
    "stats": [
        ("30+", "Years in Islamabad"),
        ("1 Kanal+", "Typical F-8 Plot Size"),
        ("100%", "CDA Approval Compliance"),
        ("0", "Hidden Charges in Our BOQ"),
    ],
    "challenges_h2": "What Matters on an F-8 Project",
    "challenges_sub": "Wide plots and a mixed-use neighbourhood change both the engineering and the working conditions.",
    "challenges": [
        ("📏", "Wide Spans & Structural Design",
         "F-8 plots allow genuinely open ground floors and large rooms. Those spans need engineered beam and column design — not a plan copied from a smaller sector and stretched."),
        ("🔇", "Site Discipline Near Offices & Institutions",
         "With professional and institutional buildings close by, noise timing, dust suppression and material movement need active management so the project does not generate complaints."),
        ("🏗️", "Basement & Dewatering",
         "Larger F-8 plots often support a basement. That requires shoring design, a dewatering plan for the water table and full external tanking rather than a surface-applied damp coat."),
        ("🌳", "Setbacks & Landscape Integration",
         "The generous setbacks F-8 allows are an asset. We plan the building line, plinth protection and drainage so landscaping can actually be built without compromising the waterproofing."),
    ],
    "plots_h2": "What We Build in F-8",
    "plots_sub": "Large-format residential construction and renovation across the F-8 sub-sectors.",
    "plots": [
        ("1 Kanal Residences",
         "The dominant F-8 plot size — two storeys with generous living spaces, often with a basement store or guest suite."),
        ("2 Kanal & Larger Houses",
         "Wide-frontage residences with double-height entrances, separate guest or staff blocks and substantial landscaped grounds."),
        ("Basement Construction",
         "Entertainment rooms, parking or storage basements with full external tanking and a designed dewatering approach during excavation."),
        ("Renovation & Extension",
         "Modernisation of established F-8 houses — services, kitchens, bathrooms and finishes — plus second-storey additions where the structure supports them."),
    ],
    "bylaws_h2": "CDA Approvals in F-8",
    "bylaws_sub": "Larger plots and basement work mean a more detailed submission.",
    "bylaws": [
        "Building plan approval from CDA Building Control is required before construction, based on the complete architectural and structural drawing set.",
        "Setback lines, covered-area ratio and height limits apply per plot and street width — we verify your specific plot before finalising the design.",
        "Basements require a shoring and dewatering approach as part of the submission, not as a site decision after excavation begins.",
        "Structural design must meet Islamabad's seismic zone requirements and is subject to structural vetting.",
        "Completion certificates are issued after CDA inspection confirms the built structure matches the approved drawings.",
    ],
    "faqs": [
        ("Can you build a basement on an F-8 plot?",
         "Yes — basements are common on larger F-8 plots and we build them regularly. The three critical elements are shoring design for the excavation, a real dewatering plan for the water table, and full external tanking on the basement walls and floor. A bitumen coat applied to the outside face is not a basement waterproofing system, and treating it as one is the single most common cause of damp basements in Islamabad."),
        ("What does construction cost in F-8?",
         "F-8 prices sit near the top of the Islamabad range because plots are large, spans are wide and finishing expectations are high. We work from an itemised BOQ with named material brands rather than a flat square-foot rate, so each stage — structure, waterproofing, services, finishing — is costed and visible separately."),
        ("Do you renovate older F-8 houses as well as build new ones?",
         "Yes. Many F-8 houses have sound structures but outdated services, layouts and finishes. We assess what can be retained, then modernise the wiring, plumbing, kitchens, bathrooms and finishes, and add a second storey where the existing footings will carry the load."),
    ],
    "nearby": ["f-7-islamabad", "f-6-islamabad", "f-10-islamabad", "g-9-islamabad"],
    "cta_h2": "Building in F-8 Islamabad?",
    "cta_p": "Send us your plot number and we will confirm the CDA limits and prepare an itemised BOQ.",
    "wa_text": "Hello Al Sadat Builders, I need construction work in F-8 Islamabad.",
},

# ============================================================
# F-10
# ============================================================
{
    "slug": "construction-company-f-10-islamabad",
    "name": "F-10",
    "short": "F-10 Islamabad",
    "group": "sector",
    "icon": "🌲",
    "title": "Construction Company in F-10 Islamabad | Al Sadat Builders",
    "meta_desc": "Construction company in F-10 Islamabad. House construction, renovation and second-storey additions on 10 Marla and 1 Kanal plots near F-10 Markaz.",
    "keywords": "construction company in F-10 Islamabad, F-10 Islamabad builders, house construction F-10, F-10 Markaz contractor, house renovation F-10 Islamabad, 10 marla construction F-10",
    "og_title": "Construction Company in F-10 Islamabad | Al Sadat Builders",
    "h1": "Construction Company in F-10, Islamabad",
    "hero_sub": "House Construction, Renovation & Second-Storey Additions on 10 Marla and 1 Kanal Plots",
    "badge": "F-10 Construction & Renovation",
    "img": "images/corner-house-islamabad.webp",
    "img_alt": "House construction and renovation in F-10 Islamabad",
    "lead_h2": "F-10 Is a Settled Family Sector — Most Work Is Improvement, Not Replacement",
    "intro": [
        "F-10 sits beside Fatima Jinnah Park and around its own Markaz, and it has the feel of a settled family sector rather than a rebuild market. The housing stock is younger than F-6 or F-7, plots are mostly 10 Marla and 1 Kanal, and a large share of the houses here are still the original builds — sound, but increasingly dated in layout, services and finishes.",
        "That produces steady demand for renovation, kitchen and bathroom remodelling, service replacement and second-storey additions rather than wholesale rebuilds. Al Sadat Builders' work in F-10 is mostly this kind of project: keeping a structurally sound house, and bringing it up to a standard its owners are happy to live in for another twenty years.",
    ],
    "highlight": "Key point: Before quoting a renovation we check the existing wiring, plumbing and waterproofing. Replacing those while the walls are already open costs a fraction of doing it later after the new finishes are in.",
    "stats": [
        ("30+", "Years in Islamabad"),
        ("10 Marla-1 Kanal", "Typical F-10 Plots"),
        ("100%", "CDA Approval Compliance"),
        ("0", "Hidden Charges in Our BOQ"),
    ],
    "challenges_h2": "What Matters on an F-10 Project",
    "challenges_sub": "Most F-10 work happens inside and around a house that stays standing.",
    "challenges": [
        ("🔌", "Replacing Services While Walls Are Open",
         "Original wiring and plumbing in a 20 to 30 year old house rarely meets current demand. We replace them during the renovation rather than patching, because doing it later means reopening finished walls."),
        ("⬆️", "Second-Storey Additions on Existing Footings",
         "Many F-10 houses were built for a single storey. Before adding above, we verify the existing footings and design strengthening where required so the addition does not overload what is underneath."),
        ("💧", "Damp, Efflorescence & Plinth Protection",
         "Older houses commonly show rising damp and salt staining. We address the cause — DPC condition, plinth protection, drainage falls — instead of repeatedly repainting over the symptom."),
        ("🏠", "Living Through a Renovation",
         "Many F-10 clients stay in the house during the work. We phase the project and sequence dusty operations so parts of the home remain usable throughout."),
    ],
    "plots_h2": "What We Build in F-10",
    "plots_sub": "Renovation, extension and new construction across the F-10 sub-sectors.",
    "plots": [
        ("10 Marla Houses",
         "The most common F-10 plot. Renovations here focus on opening up ground floors, modernising kitchens and adding a bedroom or two where the plan allows."),
        ("1 Kanal Houses",
         "Full interior modernisation with upgraded services, imported sanitary, custom joinery and false ceilings, plus optional basement or store."),
        ("Second-Storey Additions",
         "Adding a full upper floor with independent column framing, connected properly to the existing structure and designed within CDA height limits."),
        ("Kitchen & Bathroom Remodelling",
         "Targeted projects converting dated kitchens and bathrooms into modern layouts with concealed plumbing, proper waterproofing membranes and upgraded tiling."),
    ],
    "bylaws_h2": "CDA Approvals in F-10",
    "bylaws_sub": "Extensions count as construction work here — they need approval too.",
    "bylaws": [
        "Building plan approval from CDA is required for extensions and structural changes, not only for new builds.",
        "Adding a storey changes the approved height and covered area, so the addition must be submitted and approved before work starts.",
        "Setback lines and covered-area limits apply to your specific plot — we verify these before designing any extension.",
        "Structural design must satisfy Islamabad's seismic zone requirements and is subject to vetting.",
        "Completion certificates follow CDA inspection confirming the built structure matches the approved drawings.",
    ],
    "faqs": [
        ("Can I add a second storey to my F-10 house?",
         "Usually yes, after we check the existing foundation. Many F-10 houses were designed for a single storey, so the footings may need strengthening before additional load is applied. We inspect first, then design the extension and any strengthening work together and submit the revised drawings to CDA."),
        ("Is it worth renovating or should I rebuild?",
         "Most F-10 houses have sound structures, which makes renovation the better value. We inspect the frame, footings and brickwork, and if they are in good condition we renovate. If we find serious structural problems, we say so and explain what a rebuild would involve — but we do not push a rebuild onto a house that does not need one."),
        ("How much does renovation cost in F-10?",
         "Renovation cost depends almost entirely on how much you replace. Cosmetic work — paint, tiling, fittings — is a fraction of the cost of replacing wiring, plumbing and waterproofing throughout. We provide an itemised BOQ separating each element so you can decide how far to go and see exactly what each decision costs."),
    ],
    "nearby": ["f-11-islamabad", "f-8-islamabad", "g-10-islamabad", "g-11-islamabad"],
    "cta_h2": "Renovating or Building in F-10?",
    "cta_p": "We will inspect your existing house and give you an honest renovation-versus-rebuild assessment.",
    "wa_text": "Hello Al Sadat Builders, I need construction or renovation work in F-10 Islamabad.",
},

# ============================================================
# F-11
# ============================================================
{
    "slug": "construction-company-f-11-islamabad",
    "name": "F-11",
    "short": "F-11 Islamabad",
    "group": "sector",
    "icon": "🏗️",
    "title": "Construction Company in F-11 Islamabad | Al Sadat Builders",
    "meta_desc": "Construction company in F-11 Islamabad. New house construction, grey structure and renovation on 10 Marla and 1 Kanal plots near F-11 Markaz.",
    "keywords": "construction company in F-11 Islamabad, F-11 Islamabad builders, house construction F-11, F-11 Markaz contractor, grey structure F-11 Islamabad, 1 kanal construction F-11",
    "og_title": "Construction Company in F-11 Islamabad | Al Sadat Builders",
    "h1": "Construction Company in F-11, Islamabad",
    "hero_sub": "New House Construction, Grey Structure & Renovation Across F-11/1 to F-11/4 and F-11 Markaz",
    "badge": "F-11 New Builds & Renovation",
    "img": "images/grey-structure-site.webp",
    "img_alt": "Grey structure house construction in F-11 Islamabad",
    "lead_h2": "F-11 Has More Empty and Newly Built Plots Than Its Neighbours",
    "intro": [
        "F-11 was developed later than F-6, F-7 and F-10, and its build-out is still visibly uneven — fully established streets sit a short walk from plots that were only recently built or are still empty. Plot sizes run mostly to 10 Marla and 1 Kanal across the F-11/1 to F-11/4 sub-sectors, with the F-11 Markaz serving as the commercial centre.",
        "That mix means F-11 projects are more often first builds and grey-structure jobs than the deep renovation work you find in the older sectors. Building on a plot with empty or partially built neighbours brings its own practical set of issues — site access, water availability during construction, and protecting your finished work from adjacent excavation. Al Sadat Builders plans the sequence around those conditions.",
    ],
    "highlight": "Key point: On a plot with construction happening next door, your newly completed finishes are at risk from their excavation. We plan party-wall protection and external waterproofing as part of your scope, not as an afterthought.",
    "stats": [
        ("30+", "Years in Islamabad"),
        ("10 Marla-1 Kanal", "Typical F-11 Plots"),
        ("100%", "CDA Approval Compliance"),
        ("0", "Hidden Charges in Our BOQ"),
    ],
    "challenges_h2": "What Matters on an F-11 Project",
    "challenges_sub": "A sector mid build-out creates conditions you do not get in a fully settled one.",
    "challenges": [
        ("🚧", "Adjacent Construction & Party-Wall Protection",
         "Excavation next door can undermine your foundation and expose your walls. We design footings and external waterproofing with neighbouring construction in mind and protect shared boundaries."),
        ("🚰", "Water for Construction & Long-Term Storage",
         "Building water is not always freely available on a developing street. We plan construction water supply and, separately, size your permanent underground and overhead tanks so the household is not affected by supply variability."),
        ("📐", "First-Build Design Within CDA Limits",
         "On a fresh plot there is no existing footprint to work around, but the setback, coverage and height rules still define what you can build. We design to those limits from the first sketch."),
        ("🧱", "Grey Structure Quality on New Builds",
         "A large share of F-11 work is grey structure. Steel grade, tie spacing, concrete mix and curing are what determine whether the house is still sound in thirty years, and that is where we refuse to economise."),
    ],
    "plots_h2": "What We Build in F-11",
    "plots_sub": "New construction, grey structure and modernisation across the F-11 sub-sectors.",
    "plots": [
        ("10 Marla New Builds",
         "Efficient two-storey family homes planned around light wells and a practical stair core, built to CDA's coverage and height limits."),
        ("1 Kanal Houses",
         "Full turnkey builds with generous living spaces, covered parking, guest accommodation and contemporary elevations."),
        ("Grey Structure Only",
         "Complete grey structure to specification for owners who want to handle finishing themselves or complete it in stages later."),
        ("Renovation of Earlier Builds",
         "Updating houses built in F-11's earlier phases — new services, modernised kitchens and bathrooms, and improved thermal and waterproofing performance."),
    ],
    "bylaws_h2": "CDA Approvals in F-11",
    "bylaws_sub": "First builds on a developing street still follow the standard CDA route.",
    "bylaws": [
        "Building plan approval from CDA Building Control is required before construction begins, based on the full drawing set.",
        "Setback lines, covered-area ratio and maximum permissible height depend on your plot size and street width — we verify before designing.",
        "Structural design must satisfy Islamabad's seismic zone requirements and undergoes structural vetting.",
        "Party-wall and boundary treatment is governed by CDA rules, which matters where neighbouring plots are under construction.",
        "A completion certificate is issued after CDA inspection confirms the structure matches the approved drawings.",
    ],
    "faqs": [
        ("How much does it cost to build a 10 Marla house in F-11?",
         "It depends on specification and how much of the plot you build over. We provide an itemised BOQ with named material brands after a free site visit, with grey structure and finishing costed as separate sections. That structure lets you see exactly where the money goes and make deliberate choices about where to upgrade."),
        ("Do you build grey structure only in F-11?",
         "Yes, and it is a common request here. We build the complete grey structure to specification — foundation, RCC frame, brickwork, conduits and rough plumbing — and hand over a clean, documented shell. You can then finish it in stages or with a different contractor, starting from a known sound state."),
        ("My neighbour is also building. Does that affect my project?",
         "It can, and it is worth planning for. Adjacent excavation can undermine a boundary, and water from their site can damage your new finishes. We protect shared boundaries, waterproof external faces on the affected side, and where necessary discuss sequencing so the two projects do not damage each other."),
    ],
    "nearby": ["f-10-islamabad", "g-10-islamabad", "g-11-islamabad", "e-11-islamabad"],
    "cta_h2": "Building in F-11 Islamabad?",
    "cta_p": "Send us your plot number and street. We will confirm the CDA limits and prepare an itemised BOQ.",
    "wa_text": "Hello Al Sadat Builders, I need construction work in F-11 Islamabad.",
},

# ============================================================
# G-6
# ============================================================
{
    "slug": "construction-company-g-6-islamabad",
    "name": "G-6",
    "short": "G-6 Islamabad",
    "group": "sector",
    "icon": "🏪",
    "title": "Construction Company in G-6 Islamabad | Al Sadat Builders",
    "meta_desc": "Construction company in G-6 Islamabad. House construction, structural rebuilds and renovation around Melody Market and the Blue Area edge. 30+ years.",
    "keywords": "construction company in G-6 Islamabad, G-6 Islamabad builders, house construction G-6, Melody Market contractor, house renovation G-6 Islamabad, G-6 Blue Area construction",
    "og_title": "Construction Company in G-6 Islamabad | Al Sadat Builders",
    "h1": "Construction Company in G-6, Islamabad",
    "hero_sub": "Renovation, Structural Rebuilds & Construction Around Melody Market and the Blue Area Edge",
    "badge": "G-6 Renovation & Rebuild",
    "img": "images/corner-house-islamabad.webp",
    "img_alt": "House renovation and construction in G-6 Islamabad near Melody Market",
    "lead_h2": "G-6 Is Old, Central and Constantly Under Pressure",
    "intro": [
        "G-6 is one of Islamabad's oldest sectors, and it sits immediately against the Blue Area and the Melody Market commercial centre. The result is a sector with a genuinely mixed character: established family homes on quiet interior streets, commercial frontage along the main roads, and decades of incremental modification layered onto the original housing stock.",
        "That layering is what makes G-6 work different. Structures here have often been altered several times — walls opened, rooms added, services extended — usually without any consistent structural record. Before we quote anything in G-6 we survey what is actually there, because the original drawings rarely describe the house that is standing on the plot today.",
    ],
    "highlight": "Key point: In G-6, unrecorded past modifications are the biggest hidden risk. We survey the structure as-built rather than trusting drawings that may describe a very different house.",
    "stats": [
        ("30+", "Years in Islamabad"),
        ("10 Marla-1 Kanal", "Typical G-6 Plots"),
        ("100%", "CDA Approval Compliance"),
        ("0", "Hidden Charges in Our BOQ"),
    ],
    "challenges_h2": "What Makes G-6 Projects Tricky",
    "challenges_sub": "Age, density and mixed-use pressure all compound each other here.",
    "challenges": [
        ("🔍", "Surveying Decades of Unrecorded Modifications",
         "Walls opened, extensions added, services rerouted — often without documentation. We inspect the structure as it actually stands before recommending any scope of work."),
        ("🧱", "Load-Bearing Walls & Limited Openings",
         "Many G-6 houses are built on load-bearing brick. Opening a plan requires properly designed beams and lintels, and some walls genuinely cannot be removed without compromising the structure."),
        ("🚗", "Tight Streets & Parking Pressure",
         "G-6's interior streets are narrow and heavily parked, with commercial traffic on the main roads. Excavation spoil, concrete deliveries and material staging need tight scheduling to stay workable."),
        ("🏬", "Residential Work Beside Commercial Use",
         "Where homes sit alongside commercial frontage, working hours, noise and site security need managing differently than on a purely residential street."),
    ],
    "plots_h2": "What We Build in G-6",
    "plots_sub": "Renovation, rebuild and modernisation across the G-6 sub-sectors.",
    "plots": [
        ("10 Marla Houses",
         "A major share of G-6 housing. Renovations focus on opening the ground floor within structural limits and modernising services and finishes throughout."),
        ("1 Kanal Houses",
         "Larger family homes, frequently rebuilt behind the original street line to deliver a contemporary layout within current CDA limits."),
        ("Structural Rebuilds",
         "Where the existing load-bearing structure cannot support the plan wanted, we demolish and build a new RCC frame on the same plot with full CDA approval."),
        ("Service Replacement",
         "Complete rewiring and replumbing of houses whose original services are decades past their design life — done while walls are open during renovation."),
    ],
    "bylaws_h2": "CDA Approvals in G-6",
    "bylaws_sub": "Decades of unauthorised alterations are common here — approvals catch them.",
    "bylaws": [
        "Building plan approval from CDA is required for rebuilds, extensions and structural alterations.",
        "Setback lines and covered-area limits may differ from those the original house was built under — we confirm the current rules for your plot.",
        "Structural design must meet Islamabad's seismic zone requirements and is subject to CDA structural vetting.",
        "Where a property has mixed residential and commercial use, additional CDA conditions may apply — we confirm these before design.",
        "Completion certificates require CDA inspection confirming the built structure matches the approved drawings.",
    ],
    "faqs": [
        ("My G-6 house has been modified over the years. Can you still work with it?",
         "Yes, and this is normal in G-6. The key step is surveying the structure as it actually stands rather than relying on original drawings that may no longer describe the house. We inspect the footings, walls and any past structural alterations, then tell you clearly what can be kept, what needs strengthening and what should be replaced."),
        ("Can I remove an interior wall to open up my G-6 house?",
         "Sometimes. In a load-bearing brick house, an interior wall may be carrying part of the floor or roof load — removing it without a properly designed beam above creates a real structural problem. We assess which walls are load-bearing and, where removal is possible, design the supporting beam and lintel detail to make it safe."),
        ("Do you handle CDA approval for renovation work in G-6?",
         "Yes. Structural alterations and extensions require CDA approval, not just new builds. We prepare the drawing set, coordinate the submission and build to the approved design so your completion certificate is not held up later by unapproved changes."),
    ],
    "nearby": ["g-9-islamabad", "f-6-islamabad", "f-7-islamabad", "f-8-islamabad"],
    "cta_h2": "Renovating or Rebuilding in G-6?",
    "cta_p": "We will survey your existing structure as-built and give you an honest assessment before quoting.",
    "wa_text": "Hello Al Sadat Builders, I need construction or renovation work in G-6 Islamabad.",
},

# ============================================================
# G-9
# ============================================================
{
    "slug": "construction-company-g-9-islamabad",
    "name": "G-9",
    "short": "G-9 Islamabad",
    "group": "sector",
    "icon": "🚌",
    "title": "Construction Company in G-9 Islamabad | Al Sadat Builders",
    "meta_desc": "Construction company in G-9 Islamabad. Renovation, rebuilding and new construction near Karachi Company Markaz. CDA approvals handled. 30+ years.",
    "keywords": "construction company in G-9 Islamabad, G-9 Islamabad builders, house construction G-9, Karachi Company Markaz contractor, house renovation G-9 Islamabad, G-9 markaz construction",
    "og_title": "Construction Company in G-9 Islamabad | Al Sadat Builders",
    "h1": "Construction Company in G-9, Islamabad",
    "hero_sub": "Renovation, Rebuilding & New Construction Across G-9/1 to G-9/4 and Karachi Company Markaz",
    "badge": "G-9 Construction & Renovation",
    "img": "images/corner-house-islamabad.webp",
    "img_alt": "House construction and renovation in G-9 Islamabad",
    "lead_h2": "G-9 Is Dense, Well Connected and Constantly Being Upgraded",
    "intro": [
        "G-9 sits alongside Karachi Company Markaz and one of the city's busier transport interchanges, which makes it unusually well connected and unusually busy for a residential sector. Plot sizes are predominantly 10 Marla and 1 Kanal across the G-9/1 to G-9/4 sub-sectors, and the housing stock is a mix of original builds and houses that have been renovated or extended over the years.",
        "The work here leans toward renovation, extension and finishing — updating kitchens and bathrooms, adding a storey, replacing services, and fixing the damp and waterproofing problems that decades of Islamabad monsoons inevitably produce. Al Sadat Builders handles the full scope in G-9, from a single bathroom rebuild to a complete house modernisation.",
    ],
    "highlight": "Key point: Damp and efflorescence in older G-9 houses is almost always a drainage and DPC problem, not a paint problem. We fix the cause before any new finish goes on the wall.",
    "stats": [
        ("30+", "Years in Islamabad"),
        ("10 Marla-1 Kanal", "Typical G-9 Plots"),
        ("100%", "CDA Approval Compliance"),
        ("0", "Hidden Charges in Our BOQ"),
    ],
    "challenges_h2": "What Matters on a G-9 Project",
    "challenges_sub": "Density and age define the working conditions here.",
    "challenges": [
        ("💧", "Rising Damp, Efflorescence & Waterproofing",
         "Older G-9 houses commonly show salt staining and damp patches. We trace it to its source — failing DPC, absent plinth protection, poor drainage falls — and correct the cause before new finishes are applied."),
        ("🔌", "Aging Electrical & Plumbing Services",
         "Original wiring and pipework rarely suit modern loads. We replace services properly during renovation rather than adding to a system already past its design life."),
        ("🚧", "Narrow Interior Streets & Access",
         "G-9's internal streets are narrow and busy. Excavation spoil removal, concrete delivery and material staging need careful scheduling to keep the street usable for neighbours."),
        ("⬆️", "Storey Additions Within Height Limits",
         "Adding an upper floor requires both structural verification of the existing footings and compliance with CDA's height and covered-area limits — we check both before designing."),
    ],
    "plots_h2": "What We Build in G-9",
    "plots_sub": "Renovation, extension and new construction across the G-9 sub-sectors.",
    "plots": [
        ("10 Marla Houses",
         "G-9's most common plot size. Renovations typically open the ground floor, add a bedroom and modernise the kitchen, bathrooms and services."),
        ("1 Kanal Houses",
         "Full modernisation or rebuild — upgraded services, contemporary joinery, imported sanitary and improved waterproofing throughout."),
        ("Second-Storey Additions",
         "Upper floors added with independent column framing, designed within CDA height limits and supported by verified or strengthened existing footings."),
        ("Kitchen, Bathroom & Tiling Work",
         "Targeted projects with proper waterproofing membranes, concealed plumbing and precision tile and marble installation."),
    ],
    "bylaws_h2": "CDA Approvals in G-9",
    "bylaws_sub": "Adding a floor is the most common submission we handle in this sector.",
    "bylaws": [
        "Building plan approval from CDA is required for new construction, extensions and structural alterations.",
        "Height and covered-area limits apply per plot and street — adding a storey requires a revised submission and approval.",
        "Setback lines are set by CDA and we verify the current requirements for your specific plot before designing.",
        "Structural design must satisfy Islamabad's seismic zone requirements and is subject to structural vetting.",
        "Completion certificates follow CDA inspection confirming the built structure matches the approved drawings.",
    ],
    "faqs": [
        ("Why do the walls in my older G-9 house keep getting damp patches?",
         "In almost every case it is moisture from below or outside the wall rather than a paint failure. Failing damp-proof course, missing plinth protection, poor drainage falls around the building and unsealed external faces all let water into the masonry, and the salts it carries show up as efflorescence. Repainting over it looks fine for one season and then returns. We trace and correct the source, then finish the wall properly."),
        ("Can I add another floor to my G-9 house?",
         "Often yes, subject to two checks. First, the existing footings and walls have to be capable of carrying the extra load — many single-storey houses in this sector were not designed for a second floor and need strengthening. Second, the addition has to comply with CDA's height and covered-area limits, which means a revised submission and approval before work starts."),
        ("How much does renovation cost in G-9?",
         "It depends on how much you replace. A targeted kitchen and bathroom renovation costs a fraction of a whole-house modernisation with full service replacement. We provide an itemised BOQ separating structure, waterproofing, services and finishing so you can see the cost of each element and decide the scope deliberately."),
    ],
    "nearby": ["g-10-islamabad", "g-6-islamabad", "f-8-islamabad", "g-11-islamabad"],
    "cta_h2": "Renovating or Building in G-9?",
    "cta_p": "Tell us what needs fixing. We will inspect the house and give you an itemised, staged quotation.",
    "wa_text": "Hello Al Sadat Builders, I need construction or renovation work in G-9 Islamabad.",
},

# ============================================================
# G-10
# ============================================================
{
    "slug": "construction-company-g-10-islamabad",
    "name": "G-10",
    "short": "G-10 Islamabad",
    "group": "sector",
    "icon": "🏘️",
    "title": "Construction Company in G-10 Islamabad | Al Sadat Builders",
    "meta_desc": "Construction company in G-10 Islamabad. House construction, renovation and grey structure on 10 Marla and 1 Kanal plots. CDA approvals handled.",
    "keywords": "construction company in G-10 Islamabad, G-10 Islamabad builders, house construction G-10, G-10 Markaz contractor, house renovation G-10 Islamabad, 10 marla construction G-10",
    "og_title": "Construction Company in G-10 Islamabad | Al Sadat Builders",
    "h1": "Construction Company in G-10, Islamabad",
    "hero_sub": "House Construction, Renovation & Grey Structure Across G-10/1 to G-10/4",
    "badge": "G-10 Construction & Renovation",
    "img": "images/grey-structure-site.webp",
    "img_alt": "Grey structure and house construction in G-10 Islamabad",
    "lead_h2": "G-10 Is a Straightforward Family Sector — and That Suits Careful Building",
    "intro": [
        "G-10 is a settled residential sector built around its own Markaz, with plot sizes running mostly to 10 Marla and 1 Kanal across the G-10/1 to G-10/4 sub-sectors. Unlike the commercial-heavy sectors nearby, it is predominantly residential, which makes for cleaner working conditions and a more consistent standard along each street.",
        "Housing stock in G-10 is a genuine mix: original builds that have never been touched, houses renovated once a decade ago, and a steady trickle of demolish-and-rebuild projects where the land value now justifies a new house. Because the sector is residential and reasonably accessible, G-10 is a good environment for careful, unhurried construction — and we build these projects with the same structural standard we apply to the highest-specification work elsewhere.",
    ],
    "highlight": "Key point: A 10 Marla family home in G-10 gets the same Grade 60 steel, the same cure schedule and the same waterproofing detail as a 2 Kanal villa. Specification changes; structural standard does not.",
    "stats": [
        ("30+", "Years in Islamabad"),
        ("10 Marla-1 Kanal", "Typical G-10 Plots"),
        ("100%", "CDA Approval Compliance"),
        ("0", "Hidden Charges in Our BOQ"),
    ],
    "challenges_h2": "What We Handle in G-10",
    "challenges_sub": "Practical issues that shape how a G-10 build runs.",
    "challenges": [
        ("📐", "Making a 10 Marla Plot Work Hard",
         "On a fixed footprint, stair position, light wells and circulation decide whether the house feels cramped or comfortable. We plan those first rather than squeezing rooms into whatever is left."),
        ("💧", "Waterproofing the Whole Envelope",
         "Roof, bathrooms, plinth and external faces all need proper treatment in an Islamabad climate. We build the waterproofing into the structural stage rather than applying it as a final decoration."),
        ("⬆️", "Storey Additions & Existing Footings",
         "Many G-10 houses were built as single storeys. Before adding above, we verify the existing foundation and design strengthening where it is needed."),
        ("🔌", "Upgrading Services in Dated Houses",
         "Where a house is being renovated rather than rebuilt, replacing wiring and plumbing at that point is far cheaper than reopening finished walls two years later."),
    ],
    "plots_h2": "What We Build in G-10",
    "plots_sub": "New construction, renovation and grey structure across the G-10 sub-sectors.",
    "plots": [
        ("5 & 7 Marla Houses",
         "Compact family homes where careful planning of stairs, light wells and storage decides how livable the finished house actually is."),
        ("10 Marla Houses",
         "The most common G-10 plot — two storeys with a proper lounge, three or four bedrooms and a usable covered car porch."),
        ("1 Kanal Houses",
         "Larger family residences with guest accommodation, landscaped frontage and the structural spans to allow genuinely open living spaces."),
        ("Grey Structure Only",
         "Complete grey structure built to specification for owners who want to complete finishing themselves or in stages as budget allows."),
    ],
    "bylaws_h2": "CDA Approvals in G-10",
    "bylaws_sub": "Straightforward sector, but the drawing set still has to be complete.",
    "bylaws": [
        "Building plan approval from CDA Building Control is required before construction, on the basis of a complete drawing set.",
        "Setback lines, covered-area ratio and height limits depend on plot size and street width — we verify your plot before design.",
        "Structural design must meet Islamabad's seismic zone requirements and undergoes structural vetting.",
        "Extensions and storey additions require a revised submission and approval, not just new construction.",
        "A completion certificate is issued after CDA inspection confirms the structure matches the approved drawings.",
    ],
    "faqs": [
        ("What does it cost to build a 10 Marla house in G-10?",
         "The cost depends on how much of the plot you build over and the specification you choose. We do not quote a flat per-square-foot figure — after a free site visit you get an itemised BOQ with named material brands, with grey structure and finishing shown as separate sections so you can see the cost of each stage and adjust deliberately."),
        ("Do you build grey structure only in G-10?",
         "Yes. Lots of clients build the grey structure first and complete the finishing later in stages as funds allow. We hand over a clean, documented shell built to full specification, so whenever you are ready to finish, the starting point is known and sound."),
        ("Can I extend my existing G-10 house instead of rebuilding?",
         "In most cases yes. We inspect the existing structure first — if the footings and walls are sound, an extension or second storey is usually the better value. If we find structural problems, we will tell you honestly and explain what a rebuild would cost, so the decision is based on the actual condition of your house rather than an assumption."),
    ],
    "nearby": ["g-11-islamabad", "g-9-islamabad", "f-10-islamabad", "f-11-islamabad"],
    "cta_h2": "Building in G-10 Islamabad?",
    "cta_p": "Send us your plot number and street. We will confirm the CDA limits and prepare an itemised BOQ.",
    "wa_text": "Hello Al Sadat Builders, I need construction work in G-10 Islamabad.",
},

# ============================================================
# G-11
# ============================================================
{
    "slug": "construction-company-g-11-islamabad",
    "name": "G-11",
    "short": "G-11 Islamabad",
    "group": "sector",
    "icon": "🛣️",
    "title": "Construction Company in G-11 Islamabad | Al Sadat Builders",
    "meta_desc": "Construction company in G-11 Islamabad. New house construction, grey structure and renovation on 10 Marla and 1 Kanal plots near G-11 Markaz.",
    "keywords": "construction company in G-11 Islamabad, G-11 Islamabad builders, house construction G-11, G-11 Markaz contractor, grey structure G-11 Islamabad, 1 kanal construction G-11",
    "og_title": "Construction Company in G-11 Islamabad | Al Sadat Builders",
    "h1": "Construction Company in G-11, Islamabad",
    "hero_sub": "New Construction, Grey Structure & Renovation Across G-11/1 to G-11/4",
    "badge": "G-11 Construction & Renovation",
    "img": "images/grey-structure-site.webp",
    "img_alt": "House construction and grey structure in G-11 Islamabad",
    "lead_h2": "G-11 Combines Good Access With a Still-Evolving Housing Stock",
    "intro": [
        "G-11 sits close to Kashmir Highway, which makes it one of the better-connected G-series sectors for moving materials and machinery onto site. Plot sizes run mostly to 10 Marla and 1 Kanal across the G-11/1 to G-11/4 sub-sectors, and the Markaz gives the sector a well-developed commercial core.",
        "The housing stock is younger than G-6 or G-9, so the balance of work tilts toward new construction and first builds rather than heavy renovation — with a steady stream of second-storey additions on houses built a decade or two ago. That easier site access matters more than it sounds: it keeps concrete pours continuous and spoil removal quick, which protects both your timeline and your neighbours' patience.",
    ],
    "highlight": "Key point: On a house built 15 or 20 years ago, the original footings may or may not be sized for another storey. We verify before designing the addition, because strengthening later is far more disruptive than planning for it now.",
    "stats": [
        ("30+", "Years in Islamabad"),
        ("10 Marla-1 Kanal", "Typical G-11 Plots"),
        ("100%", "CDA Approval Compliance"),
        ("0", "Hidden Charges in Our BOQ"),
    ],
    "challenges_h2": "What We Handle in G-11",
    "challenges_sub": "New builds, additions and modernisation each bring different priorities.",
    "challenges": [
        ("⬆️", "Storey Additions on 15-20 Year Old Houses",
         "Adding an upper floor needs the existing footings to be verified and, where necessary, strengthened. We design the extension and the strengthening together rather than treating them separately."),
        ("🧱", "Grey Structure Quality on New Builds",
         "Steel grade, tie spacing, concrete mix and curing determine whether the house is sound in thirty years. These are the items we refuse to economise on regardless of the finishing budget."),
        ("💧", "Full Envelope Waterproofing",
         "Roof, bathrooms, plinth protection and external faces all need proper treatment. We build waterproofing into the structural stage rather than applying it as a finishing afterthought."),
        ("🚧", "Managing a Live Residential Street",
         "Good highway access helps, but the internal streets are still residential. We stage deliveries and spoil removal so neighbours are not blocked and the street stays usable."),
    ],
    "plots_h2": "What We Build in G-11",
    "plots_sub": "New construction, extensions and renovation across the G-11 sub-sectors.",
    "plots": [
        ("10 Marla Houses",
         "G-11's most common plot. Two-storey family homes with a practical stair core, light wells and enough covered parking for a family car."),
        ("1 Kanal Houses",
         "Larger residences with generous living spaces, guest accommodation and the structural spans to allow open-plan ground floors."),
        ("Second-Storey Additions",
         "Upper floors added with independent column framing, properly tied to the existing structure and designed within CDA height limits."),
        ("Grey Structure Only",
         "Complete structural shell built to specification for owners who want to complete finishing in stages or handle it themselves."),
    ],
    "bylaws_h2": "CDA Approvals in G-11",
    "bylaws_sub": "New builds and storey additions follow the same approval route.",
    "bylaws": [
        "Building plan approval from CDA is required before mobilisation, on the basis of a complete architectural and structural drawing set.",
        "Setback lines, covered-area ratio and permissible height depend on your plot size and street width — we confirm before designing.",
        "Storey additions change the approved height and covered area, so a revised submission and approval are required.",
        "Structural design must satisfy Islamabad's seismic zone requirements and is subject to structural vetting.",
        "Completion certificates require CDA inspection confirming the built structure matches the approved drawings.",
    ],
    "faqs": [
        ("How much does construction cost in G-11?",
         "It depends on plot size, how much you build over, and your specification. We quote from an itemised BOQ with named material brands rather than a blanket per-square-foot rate, so each stage is visible and you can decide where to specify premium and where standard specification is perfectly adequate."),
        ("Can you add a second floor to my G-11 house?",
         "Usually yes, after we check the existing foundation. Houses built fifteen or twenty years ago were often designed for a single storey, so the footings may need strengthening before extra load is applied. We inspect first, then design the addition and any strengthening together and submit the revised drawings to CDA."),
        ("Do you handle CDA approval as well as the construction?",
         "Yes. We prepare the architectural drawings, structural design and services layout, coordinate the CDA submission and build strictly to the approved set. Handling both means there is no gap between what was approved and what gets built — which is the usual reason completion certificates get delayed."),
    ],
    "nearby": ["g-10-islamabad", "g-9-islamabad", "f-11-islamabad", "e-11-islamabad"],
    "cta_h2": "Building in G-11 Islamabad?",
    "cta_p": "Tell us your plot size and street. We will confirm the CDA limits and prepare an itemised BOQ.",
    "wa_text": "Hello Al Sadat Builders, I need construction work in G-11 Islamabad.",
},

# ============================================================
# E-11
# ============================================================
{
    "slug": "construction-company-e-11-islamabad",
    "name": "E-11",
    "short": "E-11 Islamabad",
    "group": "sector",
    "icon": "🏗️",
    "title": "Construction Company in E-11 Islamabad | Al Sadat Builders",
    "meta_desc": "Construction company in E-11 Islamabad. 5, 8, 10 Marla and 1 Kanal house construction, grey structure and turnkey builds. CDA approvals handled.",
    "keywords": "construction company in E-11 Islamabad, E-11 Islamabad builders, house construction E-11, E-11 Markaz contractor, 5 marla construction E-11, grey structure E-11 Islamabad",
    "og_title": "Construction Company in E-11 Islamabad | Al Sadat Builders",
    "h1": "Construction Company in E-11, Islamabad",
    "hero_sub": "First Builds, Grey Structure & Turnkey Construction Across E-11/1 to E-11/4",
    "badge": "E-11 New Builds & Grey Structure",
    "img": "images/grey-structure-site.webp",
    "img_alt": "Grey structure house construction in E-11 Islamabad",
    "lead_h2": "E-11 Is the Newest Major Sector — and Mostly a First-Build Market",
    "intro": [
        "E-11 is among the last of Islamabad's major CDA sectors to be built out, and its plot structure reflects that. Alongside the 1 Kanal and 10 Marla plots found elsewhere in the city, E-11 has a substantial number of smaller 5 and 8 Marla plots — which makes it accessible to first-time builders in a way that F-6 or F-7 simply is not. The sub-sectors run E-11/1 through E-11/4, served by the E-11 Markaz.",
        "Because so much of the sector was built recently, most E-11 projects are first builds rather than renovations. That means clean ground, no existing structure to work around, and a real opportunity to get the foundation, waterproofing and services right from the beginning — which is precisely where we concentrate effort, because those are the elements you cannot easily change later.",
    ],
    "highlight": "Key point: On a first build you get exactly one chance to get the foundation and waterproofing right. Everything above them can be upgraded later; they cannot.",
    "stats": [
        ("30+", "Years in Islamabad"),
        ("5 Marla-1 Kanal", "E-11 Plot Range"),
        ("100%", "CDA Approval Compliance"),
        ("0", "Hidden Charges in Our BOQ"),
    ],
    "challenges_h2": "What Matters on an E-11 Build",
    "challenges_sub": "First builds concentrate all the important decisions at the beginning.",
    "challenges": [
        ("🏗️", "Getting the Foundation Right First Time",
         "On a new plot there is no existing structure to reveal problems later. Excavation depth, footing size, anti-termite treatment and DPC are all one-shot decisions that determine the life of the building."),
        ("📐", "Small Plots, Efficient Plans",
         "E-11's 5 and 8 Marla plots demand careful planning. Stair position, light wells and storage placement decide whether a compact house feels comfortable or cramped."),
        ("🚰", "Water Storage & Bore Provision",
         "Sector water supply is not always constant. We size underground and overhead storage generously, and plan bore provision where the plot and sub-sector make it feasible."),
        ("🛣️", "Access on Newly Built Streets",
         "On streets where building is still active, access and staging need coordination with neighbours. We sequence deliveries and spoil removal so the street stays usable for everyone."),
    ],
    "plots_h2": "What We Build in E-11",
    "plots_sub": "First builds, grey structure and turnkey homes across the E-11 sub-sectors.",
    "plots": [
        ("5 Marla Houses",
         "The entry point into E-11. Efficient two-storey homes where the stair core and light wells drive the whole floor plan."),
        ("8 Marla Houses",
         "A comfortable middle ground allowing a proper lounge, three bedrooms and a usable covered car porch without squeezing the layout."),
        ("10 Marla Houses",
         "Room for a basement or store and a wider frontage, with structural spans to support open-plan living areas."),
        ("1 Kanal Houses",
         "Full turnkey family residences with guest accommodation, landscaped frontage and contemporary elevations built within CDA limits."),
    ],
    "bylaws_h2": "CDA Approvals in E-11",
    "bylaws_sub": "Approval is required before mobilisation on every plot in the sector.",
    "bylaws": [
        "Building plan approval from CDA Building Control is required before construction begins on any plot.",
        "Setback lines, covered-area ratio and maximum height depend on your plot size and street width — we verify your specific plot before designing.",
        "Structural design must satisfy Islamabad's seismic zone requirements and undergoes structural vetting.",
        "Service connections for water, sewer and drainage follow CDA's specified procedure for the sub-sector.",
        "A completion certificate is issued after CDA inspection confirms the built structure matches the approved drawings without deviations.",
    ],
    "faqs": [
        ("How much does it cost to build a 5 Marla house in E-11?",
         "It depends on specification and how much of the plot you build over. We provide an itemised BOQ with named material brands after a free site visit — grey structure and finishing shown separately — so you can see the cost of each stage and make deliberate choices rather than accepting a single bundled number."),
        ("Is E-11 a good sector for a first home build?",
         "It is one of the more accessible CDA sectors for first-time builders because of the smaller 5 and 8 Marla plot sizes and the fact that much of the sector is still being built out. The trade-off is that infrastructure and neighbouring construction are still active in places, which we plan around in the project sequence."),
        ("Do you handle CDA approval for a new build in E-11?",
         "Yes. We prepare the architectural drawings, structural design and services layout, coordinate the CDA submission and build strictly to the approved set. Building without approval risks a stop-work notice and delays the completion certificate — on a first build that is a delay you do not want."),
        ("Can you build grey structure only, or do you only do turnkey?",
         "Both. Many E-11 clients build the grey structure first and complete finishing in stages as budget allows. We hand over a clean, documented shell built to full specification so that whenever you are ready to finish, the starting point is known and structurally sound."),
    ],
    "nearby": ["f-11-islamabad", "g-11-islamabad", "g-10-islamabad", "b-17-multi-gardens-islamabad"],
    "cta_h2": "Building in E-11 Islamabad?",
    "cta_p": "Send us your plot number and size. We will confirm the CDA limits and prepare an itemised BOQ.",
    "wa_text": "Hello Al Sadat Builders, I need construction work in E-11 Islamabad.",
},

]
